// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bonuses.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBonusesByStudent = `-- name: CountBonusesByStudent :one
SELECT COUNT(*)
FROM bonuses
WHERE student_id = $1
  AND user_id = $2
  AND ($3::boolean IS NULL OR (used_at IS NOT NULL) = $3::boolean)
`

type CountBonusesByStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	UserID    uuid.UUID `json:"user_id"`
	Used      *bool     `json:"used"`
}

func (q *Queries) CountBonusesByStudent(ctx context.Context, arg CountBonusesByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBonusesByStudent, arg.StudentID, arg.UserID, arg.Used)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBonusesByUser = `-- name: CountBonusesByUser :one
SELECT COUNT(*)
FROM bonuses b
WHERE b.user_id = $1
  AND ($2::uuid IS NULL OR b.student_id = $2::uuid)
  AND ($3::uuid IS NULL OR b.bonus_type_id = $3::uuid)
  AND ($4::boolean IS NULL OR (b.used_at IS NOT NULL) = $4::boolean)
  AND ($5::timestamptz IS NULL OR b.occurred_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR b.occurred_at < $6::timestamptz)
  AND (
    $7::uuid IS NULL
    OR EXISTS (
      SELECT 1
      FROM student_classrooms sc
      JOIN classrooms c ON c.id = sc.classroom_id AND c.user_id = sc.user_id
      WHERE sc.student_id = b.student_id
        AND sc.user_id = b.user_id
        AND sc.classroom_id = $7::uuid
        AND c.user_id = b.user_id
    )
  )
`

type CountBonusesByUserParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	StudentID   *uuid.UUID `json:"student_id"`
	BonusTypeID *uuid.UUID `json:"bonus_type_id"`
	Used        *bool      `json:"used"`
	CreatedFrom *time.Time `json:"created_from"`
	CreatedTo   *time.Time `json:"created_to"`
	ClassroomID *uuid.UUID `json:"classroom_id"`
}

func (q *Queries) CountBonusesByUser(ctx context.Context, arg CountBonusesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBonusesByUser,
		arg.UserID,
		arg.StudentID,
		arg.BonusTypeID,
		arg.Used,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.ClassroomID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBonus = `-- name: CreateBonus :one

INSERT INTO bonuses (
    user_id, student_id, bonus_type_id, points, occurred_at, evaluation_label
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5::timestamptz, NOW()),
    COALESCE($6::text, '')
)
RETURNING
    id, user_id, student_id, bonus_type_id, points, created_at, occurred_at, evaluation_label, used_at,
    (SELECT first_name FROM students WHERE students.id = bonuses.student_id AND students.user_id = bonuses.user_id) AS student_first_name,
    (SELECT last_name FROM students WHERE students.id = bonuses.student_id AND students.user_id = bonuses.user_id) AS student_last_name,
    (SELECT name FROM bonus_types WHERE bonus_types.id = bonuses.bonus_type_id AND bonus_types.user_id = bonuses.user_id) AS bonus_type_name
`

type CreateBonusParams struct {
	UserID          uuid.UUID  `json:"user_id"`
	StudentID       uuid.UUID  `json:"student_id"`
	BonusTypeID     uuid.UUID  `json:"bonus_type_id"`
	Points          float64    `json:"points"`
	OccurredAt      *time.Time `json:"occurred_at"`
	EvaluationLabel *string    `json:"evaluation_label"`
}

type CreateBonusRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	BonusTypeID      uuid.UUID  `json:"bonus_type_id"`
	Points           float64    `json:"points"`
	CreatedAt        time.Time  `json:"created_at"`
	OccurredAt       time.Time  `json:"occurred_at"`
	EvaluationLabel  string     `json:"evaluation_label"`
	UsedAt           *time.Time `json:"used_at"`
	StudentFirstName string     `json:"student_first_name"`
	StudentLastName  string     `json:"student_last_name"`
	BonusTypeName    string     `json:"bonus_type_name"`
}

// ==================== Bonus ====================
func (q *Queries) CreateBonus(ctx context.Context, arg CreateBonusParams) (CreateBonusRow, error) {
	row := q.db.QueryRow(ctx, createBonus,
		arg.UserID,
		arg.StudentID,
		arg.BonusTypeID,
		arg.Points,
		arg.OccurredAt,
		arg.EvaluationLabel,
	)
	var i CreateBonusRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.EvaluationLabel,
		&i.UsedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.BonusTypeName,
	)
	return i, err
}

const deleteBonusByUser = `-- name: DeleteBonusByUser :execrows
DELETE FROM bonuses
WHERE id = $1 AND user_id = $2
`

type DeleteBonusByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBonusByUser(ctx context.Context, arg DeleteBonusByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBonusByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBonusByUser = `-- name: GetBonusByUser :one
SELECT
    b.id, b.user_id, b.student_id, b.bonus_type_id, b.points, b.created_at, b.occurred_at, b.evaluation_label, b.used_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    bt.name AS bonus_type_name
FROM bonuses b
JOIN students s ON s.id = b.student_id AND s.user_id = b.user_id
JOIN bonus_types bt ON bt.id = b.bonus_type_id AND bt.user_id = b.user_id
WHERE b.id = $1 AND b.user_id = $2 LIMIT 1
`

type GetBonusByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetBonusByUserRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	BonusTypeID      uuid.UUID  `json:"bonus_type_id"`
	Points           float64    `json:"points"`
	CreatedAt        time.Time  `json:"created_at"`
	OccurredAt       time.Time  `json:"occurred_at"`
	EvaluationLabel  string     `json:"evaluation_label"`
	UsedAt           *time.Time `json:"used_at"`
	StudentFirstName string     `json:"student_first_name"`
	StudentLastName  string     `json:"student_last_name"`
	BonusTypeName    string     `json:"bonus_type_name"`
}

func (q *Queries) GetBonusByUser(ctx context.Context, arg GetBonusByUserParams) (GetBonusByUserRow, error) {
	row := q.db.QueryRow(ctx, getBonusByUser, arg.ID, arg.UserID)
	var i GetBonusByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.EvaluationLabel,
		&i.UsedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.BonusTypeName,
	)
	return i, err
}

const listBonusesByStudent = `-- name: ListBonusesByStudent :many
SELECT
    b.id, b.user_id, b.student_id, b.bonus_type_id, b.points, b.created_at, b.occurred_at, b.evaluation_label, b.used_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    bt.name AS bonus_type_name
FROM bonuses b
JOIN students s ON s.id = b.student_id AND s.user_id = b.user_id
JOIN bonus_types bt ON bt.id = b.bonus_type_id AND bt.user_id = b.user_id
WHERE b.student_id = $1
  AND b.user_id = $2
  AND ($3::boolean IS NULL OR (b.used_at IS NOT NULL) = $3::boolean)
ORDER BY b.occurred_at DESC, b.id DESC
LIMIT $5 OFFSET $4
`

type ListBonusesByStudentParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	UserID      uuid.UUID `json:"user_id"`
	Used        *bool     `json:"used"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListBonusesByStudentRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	BonusTypeID      uuid.UUID  `json:"bonus_type_id"`
	Points           float64    `json:"points"`
	CreatedAt        time.Time  `json:"created_at"`
	OccurredAt       time.Time  `json:"occurred_at"`
	EvaluationLabel  string     `json:"evaluation_label"`
	UsedAt           *time.Time `json:"used_at"`
	StudentFirstName string     `json:"student_first_name"`
	StudentLastName  string     `json:"student_last_name"`
	BonusTypeName    string     `json:"bonus_type_name"`
}

func (q *Queries) ListBonusesByStudent(ctx context.Context, arg ListBonusesByStudentParams) ([]ListBonusesByStudentRow, error) {
	rows, err := q.db.Query(ctx, listBonusesByStudent,
		arg.StudentID,
		arg.UserID,
		arg.Used,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBonusesByStudentRow
	for rows.Next() {
		var i ListBonusesByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.BonusTypeID,
			&i.Points,
			&i.CreatedAt,
			&i.OccurredAt,
			&i.EvaluationLabel,
			&i.UsedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.BonusTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusesByUser = `-- name: ListBonusesByUser :many
SELECT
    b.id, b.user_id, b.student_id, b.bonus_type_id, b.points, b.created_at, b.occurred_at, b.evaluation_label, b.used_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    bt.name AS bonus_type_name
FROM bonuses b
JOIN students s ON s.id = b.student_id AND s.user_id = b.user_id
JOIN bonus_types bt ON bt.id = b.bonus_type_id AND bt.user_id = b.user_id
WHERE b.user_id = $1
  AND ($2::uuid IS NULL OR b.student_id = $2::uuid)
  AND ($3::uuid IS NULL OR b.bonus_type_id = $3::uuid)
  AND ($4::boolean IS NULL OR (b.used_at IS NOT NULL) = $4::boolean)
  AND ($5::timestamptz IS NULL OR b.occurred_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR b.occurred_at < $6::timestamptz)
  AND (
    $7::uuid IS NULL
    OR EXISTS (
      SELECT 1
      FROM student_classrooms sc
      JOIN classrooms c ON c.id = sc.classroom_id AND c.user_id = sc.user_id
      WHERE sc.student_id = b.student_id
        AND sc.user_id = b.user_id
        AND sc.classroom_id = $7::uuid
        AND c.user_id = b.user_id
    )
  )
ORDER BY b.occurred_at DESC, b.id DESC
LIMIT $9 OFFSET $8
`

type ListBonusesByUserParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	StudentID   *uuid.UUID `json:"student_id"`
	BonusTypeID *uuid.UUID `json:"bonus_type_id"`
	Used        *bool      `json:"used"`
	CreatedFrom *time.Time `json:"created_from"`
	CreatedTo   *time.Time `json:"created_to"`
	ClassroomID *uuid.UUID `json:"classroom_id"`
	QueryOffset int32      `json:"query_offset"`
	QueryLimit  int32      `json:"query_limit"`
}

type ListBonusesByUserRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	BonusTypeID      uuid.UUID  `json:"bonus_type_id"`
	Points           float64    `json:"points"`
	CreatedAt        time.Time  `json:"created_at"`
	OccurredAt       time.Time  `json:"occurred_at"`
	EvaluationLabel  string     `json:"evaluation_label"`
	UsedAt           *time.Time `json:"used_at"`
	StudentFirstName string     `json:"student_first_name"`
	StudentLastName  string     `json:"student_last_name"`
	BonusTypeName    string     `json:"bonus_type_name"`
}

func (q *Queries) ListBonusesByUser(ctx context.Context, arg ListBonusesByUserParams) ([]ListBonusesByUserRow, error) {
	rows, err := q.db.Query(ctx, listBonusesByUser,
		arg.UserID,
		arg.StudentID,
		arg.BonusTypeID,
		arg.Used,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.ClassroomID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBonusesByUserRow
	for rows.Next() {
		var i ListBonusesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.BonusTypeID,
			&i.Points,
			&i.CreatedAt,
			&i.OccurredAt,
			&i.EvaluationLabel,
			&i.UsedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.BonusTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBonusByUser = `-- name: UpdateBonusByUser :one
UPDATE bonuses
SET
    points = COALESCE($1::double precision, points),
    occurred_at = COALESCE($2::timestamptz, occurred_at),
    evaluation_label = COALESCE($3::text, evaluation_label)
WHERE bonuses.id = $4 AND bonuses.user_id = $5
RETURNING
    bonuses.id, bonuses.user_id, bonuses.student_id, bonuses.bonus_type_id, bonuses.points, bonuses.created_at, bonuses.occurred_at, bonuses.evaluation_label, bonuses.used_at,
    (SELECT first_name FROM students WHERE students.id = bonuses.student_id AND students.user_id = bonuses.user_id) AS student_first_name,
    (SELECT last_name FROM students WHERE students.id = bonuses.student_id AND students.user_id = bonuses.user_id) AS student_last_name,
    (SELECT name FROM bonus_types WHERE bonus_types.id = bonuses.bonus_type_id AND bonus_types.user_id = bonuses.user_id) AS bonus_type_name
`

type UpdateBonusByUserParams struct {
	Points          *float64   `json:"points"`
	OccurredAt      *time.Time `json:"occurred_at"`
	EvaluationLabel *string    `json:"evaluation_label"`
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
}

type UpdateBonusByUserRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	BonusTypeID      uuid.UUID  `json:"bonus_type_id"`
	Points           float64    `json:"points"`
	CreatedAt        time.Time  `json:"created_at"`
	OccurredAt       time.Time  `json:"occurred_at"`
	EvaluationLabel  string     `json:"evaluation_label"`
	UsedAt           *time.Time `json:"used_at"`
	StudentFirstName string     `json:"student_first_name"`
	StudentLastName  string     `json:"student_last_name"`
	BonusTypeName    string     `json:"bonus_type_name"`
}

func (q *Queries) UpdateBonusByUser(ctx context.Context, arg UpdateBonusByUserParams) (UpdateBonusByUserRow, error) {
	row := q.db.QueryRow(ctx, updateBonusByUser,
		arg.Points,
		arg.OccurredAt,
		arg.EvaluationLabel,
		arg.ID,
		arg.UserID,
	)
	var i UpdateBonusByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.EvaluationLabel,
		&i.UsedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.BonusTypeName,
	)
	return i, err
}

const useBonus = `-- name: UseBonus :one
UPDATE bonuses
SET used_at = NOW()
WHERE bonuses.id = $1 AND bonuses.user_id = $2 AND bonuses.used_at IS NULL
RETURNING
    bonuses.id, bonuses.user_id, bonuses.student_id, bonuses.bonus_type_id, bonuses.points, bonuses.created_at, bonuses.occurred_at, bonuses.evaluation_label, bonuses.used_at,
    (SELECT first_name FROM students WHERE students.id = bonuses.student_id AND students.user_id = bonuses.user_id) AS student_first_name,
    (SELECT last_name FROM students WHERE students.id = bonuses.student_id AND students.user_id = bonuses.user_id) AS student_last_name,
    (SELECT name FROM bonus_types WHERE bonus_types.id = bonuses.bonus_type_id AND bonus_types.user_id = bonuses.user_id) AS bonus_type_name
`

type UseBonusParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type UseBonusRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	BonusTypeID      uuid.UUID  `json:"bonus_type_id"`
	Points           float64    `json:"points"`
	CreatedAt        time.Time  `json:"created_at"`
	OccurredAt       time.Time  `json:"occurred_at"`
	EvaluationLabel  string     `json:"evaluation_label"`
	UsedAt           *time.Time `json:"used_at"`
	StudentFirstName string     `json:"student_first_name"`
	StudentLastName  string     `json:"student_last_name"`
	BonusTypeName    string     `json:"bonus_type_name"`
}

func (q *Queries) UseBonus(ctx context.Context, arg UseBonusParams) (UseBonusRow, error) {
	row := q.db.QueryRow(ctx, useBonus, arg.ID, arg.UserID)
	var i UseBonusRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.EvaluationLabel,
		&i.UsedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.BonusTypeName,
	)
	return i, err
}
