// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bonus_types.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countBonusTypesByUser = `-- name: CountBonusTypesByUser :one
SELECT COUNT(*) FROM bonus_types WHERE user_id = $1
`

func (q *Queries) CountBonusTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBonusTypesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBonusType = `-- name: CreateBonusType :one

INSERT INTO bonus_types (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateBonusTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// ==================== BonusType ====================
func (q *Queries) CreateBonusType(ctx context.Context, arg CreateBonusTypeParams) (BonusType, error) {
	row := q.db.QueryRow(ctx, createBonusType, arg.UserID, arg.Name)
	var i BonusType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBonusTypeByUser = `-- name: DeleteBonusTypeByUser :execrows
DELETE FROM bonus_types
WHERE id = $1 AND user_id = $2
`

type DeleteBonusTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBonusTypeByUser(ctx context.Context, arg DeleteBonusTypeByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBonusTypeByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBonusTypeByUser = `-- name: GetBonusTypeByUser :one
SELECT id, user_id, name, created_at, updated_at
FROM bonus_types
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetBonusTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBonusTypeByUser(ctx context.Context, arg GetBonusTypeByUserParams) (BonusType, error) {
	row := q.db.QueryRow(ctx, getBonusTypeByUser, arg.ID, arg.UserID)
	var i BonusType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBonusTypesByUser = `-- name: ListBonusTypesByUser :many
SELECT id, user_id, name, created_at, updated_at
FROM bonus_types
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListBonusTypesByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListBonusTypesByUser(ctx context.Context, arg ListBonusTypesByUserParams) ([]BonusType, error) {
	rows, err := q.db.Query(ctx, listBonusTypesByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BonusType
	for rows.Next() {
		var i BonusType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBonusTypeByUser = `-- name: UpdateBonusTypeByUser :one
UPDATE bonus_types
SET
    name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateBonusTypeByUserParams struct {
	Name   *string   `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateBonusTypeByUser(ctx context.Context, arg UpdateBonusTypeByUserParams) (BonusType, error) {
	row := q.db.QueryRow(ctx, updateBonusTypeByUser, arg.Name, arg.ID, arg.UserID)
	var i BonusType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
