// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classrooms.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countClassroomsByUser = `-- name: CountClassroomsByUser :one
SELECT COUNT(*)
FROM classrooms c
WHERE c.user_id = $1
  AND (
    $2::text IS NULL
    OR c.name ILIKE '%' || $2::text || '%'
  )
`

type CountClassroomsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Search *string   `json:"search"`
}

func (q *Queries) CountClassroomsByUser(ctx context.Context, arg CountClassroomsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClassroomsByUser, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClassroom = `-- name: CreateClassroom :one

INSERT INTO classrooms (
    user_id, name, year, main_teacher
) VALUES (
    $1, $2, $3, $4
)
RETURNING
    id, user_id, name, year, main_teacher, created_at, updated_at,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        WHERE sc.classroom_id = classrooms.id
    ), 0)::bigint AS student_count,
    COALESCE((
        SELECT SUM(b.points)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN bonuses b ON b.student_id = s.id
        WHERE sc.classroom_id = classrooms.id
          AND b.user_id = classrooms.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN penalties p ON p.student_id = s.id
        WHERE sc.classroom_id = classrooms.id
          AND p.user_id = classrooms.user_id
    ), 0)::bigint AS total_penalty_count
`

type CreateClassroomParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Year        *string   `json:"year"`
	MainTeacher *string   `json:"main_teacher"`
}

type CreateClassroomRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Year              *string   `json:"year"`
	MainTeacher       *string   `json:"main_teacher"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	StudentCount      int64     `json:"student_count"`
	TotalBonusPoints  float64   `json:"total_bonus_points"`
	TotalPenaltyCount int64     `json:"total_penalty_count"`
}

// ==================== Classroom ====================
func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (CreateClassroomRow, error) {
	row := q.db.QueryRow(ctx, createClassroom,
		arg.UserID,
		arg.Name,
		arg.Year,
		arg.MainTeacher,
	)
	var i CreateClassroomRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Year,
		&i.MainTeacher,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentCount,
		&i.TotalBonusPoints,
		&i.TotalPenaltyCount,
	)
	return i, err
}

const deleteAllClassroomsByUser = `-- name: DeleteAllClassroomsByUser :execrows
DELETE FROM classrooms
WHERE user_id = $1
`

func (q *Queries) DeleteAllClassroomsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllClassroomsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteClassroomByUser = `-- name: DeleteClassroomByUser :execrows
DELETE FROM classrooms
WHERE id = $1 AND user_id = $2
`

type DeleteClassroomByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteClassroomByUser(ctx context.Context, arg DeleteClassroomByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClassroomByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClassroomByUser = `-- name: GetClassroomByUser :one
SELECT
    c.id, c.user_id, c.name, c.year, c.main_teacher, c.created_at, c.updated_at,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        WHERE sc.classroom_id = c.id
    ), 0)::bigint AS student_count,
    COALESCE((
        SELECT SUM(b.points)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN bonuses b ON b.student_id = s.id
        WHERE sc.classroom_id = c.id
          AND b.user_id = c.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN penalties p ON p.student_id = s.id
        WHERE sc.classroom_id = c.id
          AND p.user_id = c.user_id
    ), 0)::bigint AS total_penalty_count
FROM classrooms c
WHERE c.id = $1 AND c.user_id = $2 LIMIT 1
`

type GetClassroomByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetClassroomByUserRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Year              *string   `json:"year"`
	MainTeacher       *string   `json:"main_teacher"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	StudentCount      int64     `json:"student_count"`
	TotalBonusPoints  float64   `json:"total_bonus_points"`
	TotalPenaltyCount int64     `json:"total_penalty_count"`
}

func (q *Queries) GetClassroomByUser(ctx context.Context, arg GetClassroomByUserParams) (GetClassroomByUserRow, error) {
	row := q.db.QueryRow(ctx, getClassroomByUser, arg.ID, arg.UserID)
	var i GetClassroomByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Year,
		&i.MainTeacher,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentCount,
		&i.TotalBonusPoints,
		&i.TotalPenaltyCount,
	)
	return i, err
}

const listClassroomsByUser = `-- name: ListClassroomsByUser :many
SELECT
    c.id, c.user_id, c.name, c.year, c.main_teacher, c.created_at, c.updated_at,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        WHERE sc.classroom_id = c.id
    ), 0)::bigint AS student_count,
    COALESCE((
        SELECT SUM(b.points)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN bonuses b ON b.student_id = s.id
        WHERE sc.classroom_id = c.id
          AND b.user_id = c.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN penalties p ON p.student_id = s.id
        WHERE sc.classroom_id = c.id
          AND p.user_id = c.user_id
    ), 0)::bigint AS total_penalty_count
FROM classrooms c
WHERE c.user_id = $1
  AND (
    $2::text IS NULL
    OR c.name ILIKE '%' || $2::text || '%'
  )
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type ListClassroomsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Search      *string   `json:"search"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListClassroomsByUserRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Year              *string   `json:"year"`
	MainTeacher       *string   `json:"main_teacher"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	StudentCount      int64     `json:"student_count"`
	TotalBonusPoints  float64   `json:"total_bonus_points"`
	TotalPenaltyCount int64     `json:"total_penalty_count"`
}

func (q *Queries) ListClassroomsByUser(ctx context.Context, arg ListClassroomsByUserParams) ([]ListClassroomsByUserRow, error) {
	rows, err := q.db.Query(ctx, listClassroomsByUser,
		arg.UserID,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassroomsByUserRow
	for rows.Next() {
		var i ListClassroomsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Year,
			&i.MainTeacher,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentCount,
			&i.TotalBonusPoints,
			&i.TotalPenaltyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassroomsByUserForImport = `-- name: ListClassroomsByUserForImport :many
SELECT
    c.id, c.name
FROM classrooms c
WHERE c.user_id = $1
ORDER BY c.created_at ASC, c.id ASC
`

type ListClassroomsByUserForImportRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListClassroomsByUserForImport(ctx context.Context, userID uuid.UUID) ([]ListClassroomsByUserForImportRow, error) {
	rows, err := q.db.Query(ctx, listClassroomsByUserForImport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassroomsByUserForImportRow
	for rows.Next() {
		var i ListClassroomsByUserForImportRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassroomByUser = `-- name: UpdateClassroomByUser :one
UPDATE classrooms
SET
    name = COALESCE($1, name),
    year = COALESCE($2, year),
    main_teacher = COALESCE($3, main_teacher),
    updated_at = NOW()
WHERE classrooms.id = $4 AND classrooms.user_id = $5
RETURNING
    classrooms.id, classrooms.user_id, classrooms.name, classrooms.year, classrooms.main_teacher, classrooms.created_at, classrooms.updated_at,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        WHERE sc.classroom_id = classrooms.id
    ), 0)::bigint AS student_count,
    COALESCE((
        SELECT SUM(b.points)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN bonuses b ON b.student_id = s.id
        WHERE sc.classroom_id = classrooms.id
          AND b.user_id = classrooms.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc
        JOIN students s ON s.id = sc.student_id
        JOIN penalties p ON p.student_id = s.id
        WHERE sc.classroom_id = classrooms.id
          AND p.user_id = classrooms.user_id
    ), 0)::bigint AS total_penalty_count
`

type UpdateClassroomByUserParams struct {
	Name        *string   `json:"name"`
	Year        *string   `json:"year"`
	MainTeacher *string   `json:"main_teacher"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
}

type UpdateClassroomByUserRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Year              *string   `json:"year"`
	MainTeacher       *string   `json:"main_teacher"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	StudentCount      int64     `json:"student_count"`
	TotalBonusPoints  float64   `json:"total_bonus_points"`
	TotalPenaltyCount int64     `json:"total_penalty_count"`
}

func (q *Queries) UpdateClassroomByUser(ctx context.Context, arg UpdateClassroomByUserParams) (UpdateClassroomByUserRow, error) {
	row := q.db.QueryRow(ctx, updateClassroomByUser,
		arg.Name,
		arg.Year,
		arg.MainTeacher,
		arg.ID,
		arg.UserID,
	)
	var i UpdateClassroomByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Year,
		&i.MainTeacher,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentCount,
		&i.TotalBonusPoints,
		&i.TotalPenaltyCount,
	)
	return i, err
}
