// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getDashboardKpis = `-- name: GetDashboardKpis :one

WITH filtered_students AS (
    SELECT s.id
    FROM students s
    WHERE s.user_id = $1
      AND (
        $2::uuid IS NULL
        OR EXISTS (
            SELECT 1
            FROM student_classrooms sc
            WHERE sc.student_id = s.id
              AND sc.user_id = s.user_id
              AND sc.classroom_id = $2::uuid
        )
    )
)
SELECT
    COUNT(*)::bigint AS student_count,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        JOIN filtered_students fs ON fs.id = b.student_id
        WHERE b.user_id = $1
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        JOIN filtered_students fs ON fs.id = b.student_id
        WHERE b.user_id = $1
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM bonuses b
        JOIN filtered_students fs ON fs.id = b.student_id
        WHERE b.user_id = $1
          AND b.used_at IS NULL
    ), 0)::bigint AS unused_bonus_count,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        JOIN filtered_students fs ON fs.id = p.student_id
        WHERE p.user_id = $1
    ), 0)::bigint AS penalty_count,
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        JOIN filtered_students fs ON fs.id = p.student_id
        WHERE p.user_id = $1
    ), 0)::bigint AS total_punishment_count,
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        JOIN filtered_students fs ON fs.id = p.student_id
        WHERE p.user_id = $1
          AND p.resolved_at IS NULL
          AND p.due_at < NOW()
    ), 0)::bigint AS overdue_punishment_count,
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        JOIN filtered_students fs ON fs.id = p.student_id
        WHERE p.user_id = $1
          AND p.resolved_at IS NULL
    ), 0)::bigint AS pending_punishment_count
FROM filtered_students
`

type GetDashboardKpisParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	ClassroomID *uuid.UUID `json:"classroom_id"`
}

type GetDashboardKpisRow struct {
	StudentCount           int64   `json:"student_count"`
	AvailableBonusPoints   float64 `json:"available_bonus_points"`
	TotalBonusPoints       float64 `json:"total_bonus_points"`
	UnusedBonusCount       int64   `json:"unused_bonus_count"`
	PenaltyCount           int64   `json:"penalty_count"`
	TotalPunishmentCount   int64   `json:"total_punishment_count"`
	OverduePunishmentCount int64   `json:"overdue_punishment_count"`
	PendingPunishmentCount int64   `json:"pending_punishment_count"`
}

// ==================== Dashboard ====================
func (q *Queries) GetDashboardKpis(ctx context.Context, arg GetDashboardKpisParams) (GetDashboardKpisRow, error) {
	row := q.db.QueryRow(ctx, getDashboardKpis, arg.UserID, arg.ClassroomID)
	var i GetDashboardKpisRow
	err := row.Scan(
		&i.StudentCount,
		&i.AvailableBonusPoints,
		&i.TotalBonusPoints,
		&i.UnusedBonusCount,
		&i.PenaltyCount,
		&i.TotalPunishmentCount,
		&i.OverduePunishmentCount,
		&i.PendingPunishmentCount,
	)
	return i, err
}
