// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_confirmation_tokens.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailConfirmationToken = `-- name: CreateEmailConfirmationToken :one

INSERT INTO email_confirmation_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailConfirmationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ==================== EmailConfirmationToken ====================
func (q *Queries) CreateEmailConfirmationToken(ctx context.Context, arg CreateEmailConfirmationTokenParams) (EmailConfirmationToken, error) {
	row := q.db.QueryRow(ctx, createEmailConfirmationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailConfirmationTokenByHash = `-- name: GetEmailConfirmationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM email_confirmation_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetEmailConfirmationTokenByHash(ctx context.Context, tokenHash string) (EmailConfirmationToken, error) {
	row := q.db.QueryRow(ctx, getEmailConfirmationTokenByHash, tokenHash)
	var i EmailConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateEmailConfirmationTokensByUserID = `-- name: InvalidateEmailConfirmationTokensByUserID :execrows
UPDATE email_confirmation_tokens
SET used_at = NOW()
WHERE user_id = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidateEmailConfirmationTokensByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateEmailConfirmationTokensByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailConfirmationTokenUsedByID = `-- name: MarkEmailConfirmationTokenUsedByID :execrows
UPDATE email_confirmation_tokens
SET used_at = NOW()
WHERE id = $1
  AND used_at IS NULL
`

func (q *Queries) MarkEmailConfirmationTokenUsedByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailConfirmationTokenUsedByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
