// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Bonus struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	StudentID   uuid.UUID  `json:"student_id"`
	BonusTypeID uuid.UUID  `json:"bonus_type_id"`
	Points      float64    `json:"points"`
	CreatedAt   time.Time  `json:"created_at"`
	UsedAt      *time.Time `json:"used_at"`
}

type BonusType struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Classroom struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Year        *string   `json:"year"`
	MainTeacher *string   `json:"main_teacher"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EmailConfirmationToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Penalty struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	StudentID     uuid.UUID `json:"student_id"`
	PenaltyTypeID uuid.UUID `json:"penalty_type_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type PenaltyType struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Punishment struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	PunishmentTypeID uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID *uuid.UUID `json:"triggering_rule_id"`
	CreatedAt        time.Time  `json:"created_at"`
	DueAt            time.Time  `json:"due_at"`
	ResolvedAt       *time.Time `json:"resolved_at"`
	Automated        bool       `json:"automated"`
}

type PunishmentType struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Token     string     `json:"token"`
	UserAgent string     `json:"user_agent"`
	ClientIp  string     `json:"client_ip"`
	RevokedAt *time.Time `json:"revoked_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Rule struct {
	ID                        uuid.UUID `json:"id"`
	UserID                    uuid.UUID `json:"user_id"`
	Name                      string    `json:"name"`
	ResultingPunishmentTypeID uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID             uuid.UUID `json:"penalty_type_id"`
	Threshold                 int32     `json:"threshold"`
	Mode                      string    `json:"mode"`
	IsActive                  bool      `json:"is_active"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
	DueAtAfterDays            int32     `json:"due_at_after_days"`
}

type Student struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StudentClassroom struct {
	StudentID   uuid.UUID `json:"student_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID  `json:"id"`
	Email             string     `json:"email"`
	FirstName         string     `json:"first_name"`
	LastName          string     `json:"last_name"`
	PasswordHash      string     `json:"password_hash"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	EmailVerifiedAt   *time.Time `json:"email_verified_at"`
	PasswordChangedAt *time.Time `json:"password_changed_at"`
}
