// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: penalties.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPenaltiesByStudent = `-- name: CountPenaltiesByStudent :one
SELECT COUNT(*)
FROM penalties
WHERE student_id = $1 AND user_id = $2
`

type CountPenaltiesByStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CountPenaltiesByStudent(ctx context.Context, arg CountPenaltiesByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPenaltiesByStudent, arg.StudentID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPenaltiesByStudentAndType = `-- name: CountPenaltiesByStudentAndType :one
SELECT COUNT(*)
FROM penalties
WHERE student_id = $1
  AND user_id = $2
  AND penalty_type_id = $3
`

type CountPenaltiesByStudentAndTypeParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	UserID        uuid.UUID `json:"user_id"`
	PenaltyTypeID uuid.UUID `json:"penalty_type_id"`
}

func (q *Queries) CountPenaltiesByStudentAndType(ctx context.Context, arg CountPenaltiesByStudentAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPenaltiesByStudentAndType, arg.StudentID, arg.UserID, arg.PenaltyTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPenaltiesByUser = `-- name: CountPenaltiesByUser :one
SELECT COUNT(*)
FROM penalties p
WHERE p.user_id = $1
  AND ($2::uuid IS NULL OR p.student_id = $2::uuid)
  AND ($3::uuid IS NULL OR p.penalty_type_id = $3::uuid)
  AND ($4::date IS NULL OR p.created_at >= $4::date)
  AND ($5::date IS NULL OR p.created_at < ($5::date + INTERVAL '1 day'))
  AND (
    $6::uuid IS NULL
    OR EXISTS (
      SELECT 1
      FROM student_classrooms sc
      JOIN classrooms c ON c.id = sc.classroom_id
      WHERE sc.student_id = p.student_id
        AND sc.classroom_id = $6::uuid
        AND c.user_id = p.user_id
    )
  )
`

type CountPenaltiesByUserParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	StudentID     *uuid.UUID `json:"student_id"`
	PenaltyTypeID *uuid.UUID `json:"penalty_type_id"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	ClassroomID   *uuid.UUID `json:"classroom_id"`
}

func (q *Queries) CountPenaltiesByUser(ctx context.Context, arg CountPenaltiesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPenaltiesByUser,
		arg.UserID,
		arg.StudentID,
		arg.PenaltyTypeID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.ClassroomID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPenalty = `-- name: CreatePenalty :one

INSERT INTO penalties (
    user_id, student_id, penalty_type_id
) VALUES (
    $1, $2, $3
)
RETURNING
    id, user_id, student_id, penalty_type_id, created_at,
    (SELECT first_name FROM students WHERE students.id = student_id) AS student_first_name,
    (SELECT last_name FROM students WHERE students.id = student_id) AS student_last_name,
    (SELECT name FROM penalty_types WHERE penalty_types.id = penalty_type_id) AS penalty_type_name
`

type CreatePenaltyParams struct {
	UserID        uuid.UUID `json:"user_id"`
	StudentID     uuid.UUID `json:"student_id"`
	PenaltyTypeID uuid.UUID `json:"penalty_type_id"`
}

type CreatePenaltyRow struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	StudentID        uuid.UUID `json:"student_id"`
	PenaltyTypeID    uuid.UUID `json:"penalty_type_id"`
	CreatedAt        time.Time `json:"created_at"`
	StudentFirstName string    `json:"student_first_name"`
	StudentLastName  string    `json:"student_last_name"`
	PenaltyTypeName  string    `json:"penalty_type_name"`
}

// ==================== Penalty ====================
func (q *Queries) CreatePenalty(ctx context.Context, arg CreatePenaltyParams) (CreatePenaltyRow, error) {
	row := q.db.QueryRow(ctx, createPenalty, arg.UserID, arg.StudentID, arg.PenaltyTypeID)
	var i CreatePenaltyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.PenaltyTypeID,
		&i.CreatedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.PenaltyTypeName,
	)
	return i, err
}

const deletePenaltyByUser = `-- name: DeletePenaltyByUser :execrows
DELETE FROM penalties
WHERE id = $1 AND user_id = $2
`

type DeletePenaltyByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePenaltyByUser(ctx context.Context, arg DeletePenaltyByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePenaltyByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPenaltyByUser = `-- name: GetPenaltyByUser :one
SELECT
    p.id, p.user_id, p.student_id, p.penalty_type_id, p.created_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS penalty_type_name
FROM penalties p
JOIN students s ON s.id = p.student_id
JOIN penalty_types pt ON pt.id = p.penalty_type_id
WHERE p.id = $1 AND p.user_id = $2 LIMIT 1
`

type GetPenaltyByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPenaltyByUserRow struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	StudentID        uuid.UUID `json:"student_id"`
	PenaltyTypeID    uuid.UUID `json:"penalty_type_id"`
	CreatedAt        time.Time `json:"created_at"`
	StudentFirstName string    `json:"student_first_name"`
	StudentLastName  string    `json:"student_last_name"`
	PenaltyTypeName  string    `json:"penalty_type_name"`
}

func (q *Queries) GetPenaltyByUser(ctx context.Context, arg GetPenaltyByUserParams) (GetPenaltyByUserRow, error) {
	row := q.db.QueryRow(ctx, getPenaltyByUser, arg.ID, arg.UserID)
	var i GetPenaltyByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.PenaltyTypeID,
		&i.CreatedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.PenaltyTypeName,
	)
	return i, err
}

const listPenaltiesByStudent = `-- name: ListPenaltiesByStudent :many
SELECT
    p.id, p.user_id, p.student_id, p.penalty_type_id, p.created_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS penalty_type_name
FROM penalties p
JOIN students s ON s.id = p.student_id
JOIN penalty_types pt ON pt.id = p.penalty_type_id
WHERE p.student_id = $1 AND p.user_id = $2
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPenaltiesByStudentParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListPenaltiesByStudentRow struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	StudentID        uuid.UUID `json:"student_id"`
	PenaltyTypeID    uuid.UUID `json:"penalty_type_id"`
	CreatedAt        time.Time `json:"created_at"`
	StudentFirstName string    `json:"student_first_name"`
	StudentLastName  string    `json:"student_last_name"`
	PenaltyTypeName  string    `json:"penalty_type_name"`
}

func (q *Queries) ListPenaltiesByStudent(ctx context.Context, arg ListPenaltiesByStudentParams) ([]ListPenaltiesByStudentRow, error) {
	rows, err := q.db.Query(ctx, listPenaltiesByStudent,
		arg.StudentID,
		arg.UserID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPenaltiesByStudentRow
	for rows.Next() {
		var i ListPenaltiesByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.PenaltyTypeID,
			&i.CreatedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.PenaltyTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPenaltiesByUser = `-- name: ListPenaltiesByUser :many
SELECT
    p.id, p.user_id, p.student_id, p.penalty_type_id, p.created_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS penalty_type_name
FROM penalties p
JOIN students s ON s.id = p.student_id
JOIN penalty_types pt ON pt.id = p.penalty_type_id
WHERE p.user_id = $1
  AND ($2::uuid IS NULL OR p.student_id = $2::uuid)
  AND ($3::uuid IS NULL OR p.penalty_type_id = $3::uuid)
  AND ($4::date IS NULL OR p.created_at >= $4::date)
  AND ($5::date IS NULL OR p.created_at < ($5::date + INTERVAL '1 day'))
  AND (
    $6::uuid IS NULL
    OR EXISTS (
      SELECT 1
      FROM student_classrooms sc
      JOIN classrooms c ON c.id = sc.classroom_id
      WHERE sc.student_id = p.student_id
        AND sc.classroom_id = $6::uuid
        AND c.user_id = p.user_id
    )
  )
ORDER BY p.created_at DESC
LIMIT $8 OFFSET $7
`

type ListPenaltiesByUserParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	StudentID     *uuid.UUID `json:"student_id"`
	PenaltyTypeID *uuid.UUID `json:"penalty_type_id"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	ClassroomID   *uuid.UUID `json:"classroom_id"`
	QueryOffset   int32      `json:"query_offset"`
	QueryLimit    int32      `json:"query_limit"`
}

type ListPenaltiesByUserRow struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	StudentID        uuid.UUID `json:"student_id"`
	PenaltyTypeID    uuid.UUID `json:"penalty_type_id"`
	CreatedAt        time.Time `json:"created_at"`
	StudentFirstName string    `json:"student_first_name"`
	StudentLastName  string    `json:"student_last_name"`
	PenaltyTypeName  string    `json:"penalty_type_name"`
}

func (q *Queries) ListPenaltiesByUser(ctx context.Context, arg ListPenaltiesByUserParams) ([]ListPenaltiesByUserRow, error) {
	rows, err := q.db.Query(ctx, listPenaltiesByUser,
		arg.UserID,
		arg.StudentID,
		arg.PenaltyTypeID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.ClassroomID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPenaltiesByUserRow
	for rows.Next() {
		var i ListPenaltiesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.PenaltyTypeID,
			&i.CreatedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.PenaltyTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
