// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: penalty_types.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countPenaltyTypesByUser = `-- name: CountPenaltyTypesByUser :one
SELECT COUNT(*) FROM penalty_types WHERE user_id = $1
`

func (q *Queries) CountPenaltyTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPenaltyTypesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPenaltyType = `-- name: CreatePenaltyType :one

INSERT INTO penalty_types (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name, created_at, updated_at
`

type CreatePenaltyTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// ==================== PenaltyType ====================
func (q *Queries) CreatePenaltyType(ctx context.Context, arg CreatePenaltyTypeParams) (PenaltyType, error) {
	row := q.db.QueryRow(ctx, createPenaltyType, arg.UserID, arg.Name)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePenaltyTypeByUser = `-- name: DeletePenaltyTypeByUser :execrows
DELETE FROM penalty_types
WHERE id = $1 AND user_id = $2
`

type DeletePenaltyTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePenaltyTypeByUser(ctx context.Context, arg DeletePenaltyTypeByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePenaltyTypeByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPenaltyTypeByUser = `-- name: GetPenaltyTypeByUser :one
SELECT id, user_id, name, created_at, updated_at
FROM penalty_types
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetPenaltyTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPenaltyTypeByUser(ctx context.Context, arg GetPenaltyTypeByUserParams) (PenaltyType, error) {
	row := q.db.QueryRow(ctx, getPenaltyTypeByUser, arg.ID, arg.UserID)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPenaltyTypesByUser = `-- name: ListPenaltyTypesByUser :many
SELECT id, user_id, name, created_at, updated_at
FROM penalty_types
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListPenaltyTypesByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListPenaltyTypesByUser(ctx context.Context, arg ListPenaltyTypesByUserParams) ([]PenaltyType, error) {
	rows, err := q.db.Query(ctx, listPenaltyTypesByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyType
	for rows.Next() {
		var i PenaltyType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePenaltyTypeByUser = `-- name: UpdatePenaltyTypeByUser :one
UPDATE penalty_types
SET
    name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, created_at, updated_at
`

type UpdatePenaltyTypeByUserParams struct {
	Name   *string   `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePenaltyTypeByUser(ctx context.Context, arg UpdatePenaltyTypeByUserParams) (PenaltyType, error) {
	row := q.db.QueryRow(ctx, updatePenaltyTypeByUser, arg.Name, arg.ID, arg.UserID)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
