// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: punishment_types.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countPunishmentTypesByUser = `-- name: CountPunishmentTypesByUser :one
SELECT COUNT(*)
FROM punishment_types
WHERE user_id = $1
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
  )
`

type CountPunishmentTypesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Search *string   `json:"search"`
}

func (q *Queries) CountPunishmentTypesByUser(ctx context.Context, arg CountPunishmentTypesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPunishmentTypesByUser, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPunishmentType = `-- name: CreatePunishmentType :one

INSERT INTO punishment_types (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name, created_at, updated_at
`

type CreatePunishmentTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// ==================== PunishmentType ====================
func (q *Queries) CreatePunishmentType(ctx context.Context, arg CreatePunishmentTypeParams) (PunishmentType, error) {
	row := q.db.QueryRow(ctx, createPunishmentType, arg.UserID, arg.Name)
	var i PunishmentType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePunishmentTypeByUser = `-- name: DeletePunishmentTypeByUser :execrows
DELETE FROM punishment_types
WHERE id = $1 AND user_id = $2
`

type DeletePunishmentTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePunishmentTypeByUser(ctx context.Context, arg DeletePunishmentTypeByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePunishmentTypeByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPunishmentTypeByUser = `-- name: GetPunishmentTypeByUser :one
SELECT id, user_id, name, created_at, updated_at
FROM punishment_types
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetPunishmentTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPunishmentTypeByUser(ctx context.Context, arg GetPunishmentTypeByUserParams) (PunishmentType, error) {
	row := q.db.QueryRow(ctx, getPunishmentTypeByUser, arg.ID, arg.UserID)
	var i PunishmentType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPunishmentTypesByUser = `-- name: ListPunishmentTypesByUser :many
SELECT id, user_id, name, created_at, updated_at
FROM punishment_types
WHERE user_id = $1
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
  )
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPunishmentTypesByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Search      *string   `json:"search"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListPunishmentTypesByUser(ctx context.Context, arg ListPunishmentTypesByUserParams) ([]PunishmentType, error) {
	rows, err := q.db.Query(ctx, listPunishmentTypesByUser,
		arg.UserID,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PunishmentType
	for rows.Next() {
		var i PunishmentType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePunishmentTypeByUser = `-- name: UpdatePunishmentTypeByUser :one
UPDATE punishment_types
SET
    name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, created_at, updated_at
`

type UpdatePunishmentTypeByUserParams struct {
	Name   *string   `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePunishmentTypeByUser(ctx context.Context, arg UpdatePunishmentTypeByUserParams) (PunishmentType, error) {
	row := q.db.QueryRow(ctx, updatePunishmentTypeByUser, arg.Name, arg.ID, arg.UserID)
	var i PunishmentType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
