// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: punishments.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPunishmentsByStudent = `-- name: CountPunishmentsByStudent :one
SELECT COUNT(*)
FROM punishments
WHERE student_id = $1
  AND user_id = $2
  AND ($3::boolean IS NULL OR (resolved_at IS NOT NULL) = $3::boolean)
`

type CountPunishmentsByStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	UserID    uuid.UUID `json:"user_id"`
	Resolved  *bool     `json:"resolved"`
}

func (q *Queries) CountPunishmentsByStudent(ctx context.Context, arg CountPunishmentsByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPunishmentsByStudent, arg.StudentID, arg.UserID, arg.Resolved)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPunishmentsByUser = `-- name: CountPunishmentsByUser :one
SELECT COUNT(*)
FROM punishments p
JOIN students s ON s.id = p.student_id AND s.user_id = p.user_id
WHERE p.user_id = $1
  AND ($2::boolean IS NULL OR (p.resolved_at IS NOT NULL) = $2::boolean)
  AND (
    $3::text IS NULL
    OR CONCAT_WS(' ', s.first_name, s.last_name) ILIKE '%' || $3::text || '%'
  )
`

type CountPunishmentsByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Resolved *bool     `json:"resolved"`
	Search   *string   `json:"search"`
}

func (q *Queries) CountPunishmentsByUser(ctx context.Context, arg CountPunishmentsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPunishmentsByUser, arg.UserID, arg.Resolved, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPunishment = `-- name: CreatePunishment :one

WITH created_punishment AS (
    INSERT INTO punishments (
        user_id, student_id, punishment_type_id, automated, due_at
    ) VALUES (
        $1, $2, $3, FALSE, $4
    )
    RETURNING id, user_id, student_id, punishment_type_id, triggering_rule_id, automated, created_at, due_at, resolved_at
)
SELECT
    p.id, p.user_id, p.student_id, p.punishment_type_id, p.triggering_rule_id, p.automated, p.created_at, p.due_at, p.resolved_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS punishment_type_name,
    r.name AS triggering_rule_name
FROM created_punishment p
JOIN students s ON s.id = p.student_id
JOIN punishment_types pt ON pt.id = p.punishment_type_id
LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
`

type CreatePunishmentParams struct {
	UserID           uuid.UUID `json:"user_id"`
	StudentID        uuid.UUID `json:"student_id"`
	PunishmentTypeID uuid.UUID `json:"punishment_type_id"`
	DueAt            time.Time `json:"due_at"`
}

type CreatePunishmentRow struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StudentID          uuid.UUID  `json:"student_id"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	Automated          bool       `json:"automated"`
	CreatedAt          time.Time  `json:"created_at"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	StudentFirstName   string     `json:"student_first_name"`
	StudentLastName    string     `json:"student_last_name"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
}

// ==================== Punishment ====================
func (q *Queries) CreatePunishment(ctx context.Context, arg CreatePunishmentParams) (CreatePunishmentRow, error) {
	row := q.db.QueryRow(ctx, createPunishment,
		arg.UserID,
		arg.StudentID,
		arg.PunishmentTypeID,
		arg.DueAt,
	)
	var i CreatePunishmentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.PunishmentTypeID,
		&i.TriggeringRuleID,
		&i.Automated,
		&i.CreatedAt,
		&i.DueAt,
		&i.ResolvedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.PunishmentTypeName,
		&i.TriggeringRuleName,
	)
	return i, err
}

const createPunishmentFromRule = `-- name: CreatePunishmentFromRule :one
WITH created_punishment AS (
    INSERT INTO punishments (
        user_id, student_id, punishment_type_id, triggering_rule_id, automated, due_at
    ) VALUES (
        $1, $2, $3, $4, $5, $6
    )
    RETURNING id, user_id, student_id, punishment_type_id, triggering_rule_id, automated, created_at, due_at, resolved_at
)
SELECT
    p.id, p.user_id, p.student_id, p.punishment_type_id, p.triggering_rule_id, p.automated, p.created_at, p.due_at, p.resolved_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS punishment_type_name,
    r.name AS triggering_rule_name
FROM created_punishment p
JOIN students s ON s.id = p.student_id
JOIN punishment_types pt ON pt.id = p.punishment_type_id
LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
`

type CreatePunishmentFromRuleParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	PunishmentTypeID uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID *uuid.UUID `json:"triggering_rule_id"`
	Automated        bool       `json:"automated"`
	DueAt            time.Time  `json:"due_at"`
}

type CreatePunishmentFromRuleRow struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StudentID          uuid.UUID  `json:"student_id"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	Automated          bool       `json:"automated"`
	CreatedAt          time.Time  `json:"created_at"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	StudentFirstName   string     `json:"student_first_name"`
	StudentLastName    string     `json:"student_last_name"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
}

func (q *Queries) CreatePunishmentFromRule(ctx context.Context, arg CreatePunishmentFromRuleParams) (CreatePunishmentFromRuleRow, error) {
	row := q.db.QueryRow(ctx, createPunishmentFromRule,
		arg.UserID,
		arg.StudentID,
		arg.PunishmentTypeID,
		arg.TriggeringRuleID,
		arg.Automated,
		arg.DueAt,
	)
	var i CreatePunishmentFromRuleRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.PunishmentTypeID,
		&i.TriggeringRuleID,
		&i.Automated,
		&i.CreatedAt,
		&i.DueAt,
		&i.ResolvedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.PunishmentTypeName,
		&i.TriggeringRuleName,
	)
	return i, err
}

const deletePunishmentByUser = `-- name: DeletePunishmentByUser :execrows
DELETE FROM punishments
WHERE id = $1 AND user_id = $2
`

type DeletePunishmentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePunishmentByUser(ctx context.Context, arg DeletePunishmentByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePunishmentByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPunishmentByUser = `-- name: GetPunishmentByUser :one
SELECT
    p.id, p.user_id, p.student_id, p.punishment_type_id, p.triggering_rule_id, p.automated, p.created_at, p.due_at, p.resolved_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS punishment_type_name,
    r.name AS triggering_rule_name
FROM punishments p
JOIN students s ON s.id = p.student_id
JOIN punishment_types pt ON pt.id = p.punishment_type_id
LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
WHERE p.id = $1 AND p.user_id = $2 LIMIT 1
`

type GetPunishmentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPunishmentByUserRow struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StudentID          uuid.UUID  `json:"student_id"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	Automated          bool       `json:"automated"`
	CreatedAt          time.Time  `json:"created_at"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	StudentFirstName   string     `json:"student_first_name"`
	StudentLastName    string     `json:"student_last_name"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
}

func (q *Queries) GetPunishmentByUser(ctx context.Context, arg GetPunishmentByUserParams) (GetPunishmentByUserRow, error) {
	row := q.db.QueryRow(ctx, getPunishmentByUser, arg.ID, arg.UserID)
	var i GetPunishmentByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.PunishmentTypeID,
		&i.TriggeringRuleID,
		&i.Automated,
		&i.CreatedAt,
		&i.DueAt,
		&i.ResolvedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.PunishmentTypeName,
		&i.TriggeringRuleName,
	)
	return i, err
}

const listPunishmentsByStudent = `-- name: ListPunishmentsByStudent :many
SELECT
    p.id, p.user_id, p.student_id, p.punishment_type_id, p.triggering_rule_id, p.automated, p.created_at, p.due_at, p.resolved_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS punishment_type_name,
    r.name AS triggering_rule_name
FROM punishments p
JOIN students s ON s.id = p.student_id
JOIN punishment_types pt ON pt.id = p.punishment_type_id
LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
WHERE p.student_id = $1
  AND p.user_id = $2
  AND ($3::boolean IS NULL OR (p.resolved_at IS NOT NULL) = $3::boolean)
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPunishmentsByStudentParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	UserID      uuid.UUID `json:"user_id"`
	Resolved    *bool     `json:"resolved"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListPunishmentsByStudentRow struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StudentID          uuid.UUID  `json:"student_id"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	Automated          bool       `json:"automated"`
	CreatedAt          time.Time  `json:"created_at"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	StudentFirstName   string     `json:"student_first_name"`
	StudentLastName    string     `json:"student_last_name"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
}

func (q *Queries) ListPunishmentsByStudent(ctx context.Context, arg ListPunishmentsByStudentParams) ([]ListPunishmentsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listPunishmentsByStudent,
		arg.StudentID,
		arg.UserID,
		arg.Resolved,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPunishmentsByStudentRow
	for rows.Next() {
		var i ListPunishmentsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.PunishmentTypeID,
			&i.TriggeringRuleID,
			&i.Automated,
			&i.CreatedAt,
			&i.DueAt,
			&i.ResolvedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.PunishmentTypeName,
			&i.TriggeringRuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPunishmentsByUser = `-- name: ListPunishmentsByUser :many
SELECT
    p.id, p.user_id, p.student_id, p.punishment_type_id, p.triggering_rule_id, p.automated, p.created_at, p.due_at, p.resolved_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS punishment_type_name,
    r.name AS triggering_rule_name
FROM punishments p
JOIN students s ON s.id = p.student_id
JOIN punishment_types pt ON pt.id = p.punishment_type_id
LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
WHERE p.user_id = $1
  AND ($2::boolean IS NULL OR (p.resolved_at IS NOT NULL) = $2::boolean)
  AND (
    $3::text IS NULL
    OR CONCAT_WS(' ', s.first_name, s.last_name) ILIKE '%' || $3::text || '%'
  )
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPunishmentsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Resolved    *bool     `json:"resolved"`
	Search      *string   `json:"search"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListPunishmentsByUserRow struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StudentID          uuid.UUID  `json:"student_id"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	Automated          bool       `json:"automated"`
	CreatedAt          time.Time  `json:"created_at"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	StudentFirstName   string     `json:"student_first_name"`
	StudentLastName    string     `json:"student_last_name"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
}

func (q *Queries) ListPunishmentsByUser(ctx context.Context, arg ListPunishmentsByUserParams) ([]ListPunishmentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPunishmentsByUser,
		arg.UserID,
		arg.Resolved,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPunishmentsByUserRow
	for rows.Next() {
		var i ListPunishmentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.PunishmentTypeID,
			&i.TriggeringRuleID,
			&i.Automated,
			&i.CreatedAt,
			&i.DueAt,
			&i.ResolvedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.PunishmentTypeName,
			&i.TriggeringRuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePunishment = `-- name: ResolvePunishment :one
WITH resolved_punishment AS (
    UPDATE punishments
    SET resolved_at = NOW()
    WHERE punishments.id = $1 AND punishments.user_id = $2 AND punishments.resolved_at IS NULL
    RETURNING punishments.id, punishments.user_id, punishments.student_id, punishments.punishment_type_id, punishments.triggering_rule_id, punishments.automated, punishments.created_at, punishments.due_at, punishments.resolved_at
)
SELECT
    p.id, p.user_id, p.student_id, p.punishment_type_id, p.triggering_rule_id, p.automated, p.created_at, p.due_at, p.resolved_at,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    pt.name AS punishment_type_name,
    r.name AS triggering_rule_name
FROM resolved_punishment p
JOIN students s ON s.id = p.student_id
JOIN punishment_types pt ON pt.id = p.punishment_type_id
LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
`

type ResolvePunishmentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type ResolvePunishmentRow struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StudentID          uuid.UUID  `json:"student_id"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	Automated          bool       `json:"automated"`
	CreatedAt          time.Time  `json:"created_at"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	StudentFirstName   string     `json:"student_first_name"`
	StudentLastName    string     `json:"student_last_name"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
}

func (q *Queries) ResolvePunishment(ctx context.Context, arg ResolvePunishmentParams) (ResolvePunishmentRow, error) {
	row := q.db.QueryRow(ctx, resolvePunishment, arg.ID, arg.UserID)
	var i ResolvePunishmentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.PunishmentTypeID,
		&i.TriggeringRuleID,
		&i.Automated,
		&i.CreatedAt,
		&i.DueAt,
		&i.ResolvedAt,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.PunishmentTypeName,
		&i.TriggeringRuleName,
	)
	return i, err
}
