// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addStudentToClassroom = `-- name: AddStudentToClassroom :execrows

INSERT INTO student_classrooms (student_id, classroom_id)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1 FROM students st WHERE st.id = $1 AND st.user_id = $3
) AND EXISTS (
    SELECT 1 FROM classrooms cl WHERE cl.id = $2 AND cl.user_id = $3
)
`

type AddStudentToClassroomParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// ==================== StudentClassroom ====================
func (q *Queries) AddStudentToClassroom(ctx context.Context, arg AddStudentToClassroomParams) (int64, error) {
	result, err := q.db.Exec(ctx, addStudentToClassroom, arg.StudentID, arg.ClassroomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countBonusTypesByUser = `-- name: CountBonusTypesByUser :one
SELECT COUNT(*) FROM bonus_types WHERE user_id = $1
`

func (q *Queries) CountBonusTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBonusTypesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBonusesByStudent = `-- name: CountBonusesByStudent :one
SELECT COUNT(*)
FROM bonuses
WHERE student_id = $1
  AND user_id = $2
  AND ($3::boolean IS NULL OR (used_at IS NOT NULL) = $3::boolean)
`

type CountBonusesByStudentParams struct {
	StudentID uuid.UUID   `json:"student_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Used      pgtype.Bool `json:"used"`
}

func (q *Queries) CountBonusesByStudent(ctx context.Context, arg CountBonusesByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBonusesByStudent, arg.StudentID, arg.UserID, arg.Used)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBonusesByUser = `-- name: CountBonusesByUser :one
SELECT COUNT(*)
FROM bonuses
WHERE user_id = $1
  AND ($2::boolean IS NULL OR (used_at IS NOT NULL) = $2::boolean)
`

type CountBonusesByUserParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Used   pgtype.Bool `json:"used"`
}

func (q *Queries) CountBonusesByUser(ctx context.Context, arg CountBonusesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBonusesByUser, arg.UserID, arg.Used)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClassroomsByStudent = `-- name: CountClassroomsByStudent :one
SELECT COUNT(*)
FROM student_classrooms sc
JOIN students s ON s.id = sc.student_id
WHERE sc.student_id = $1 AND s.user_id = $2
`

type CountClassroomsByStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CountClassroomsByStudent(ctx context.Context, arg CountClassroomsByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClassroomsByStudent, arg.StudentID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClassroomsByUser = `-- name: CountClassroomsByUser :one
SELECT COUNT(*) FROM classrooms WHERE user_id = $1
`

func (q *Queries) CountClassroomsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClassroomsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPenaltyTypesByUser = `-- name: CountPenaltyTypesByUser :one
SELECT COUNT(*) FROM penalty_types WHERE user_id = $1
`

func (q *Queries) CountPenaltyTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPenaltyTypesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsByClassroom = `-- name: CountStudentsByClassroom :one
SELECT COUNT(*)
FROM student_classrooms sc
JOIN classrooms c ON c.id = sc.classroom_id
WHERE sc.classroom_id = $1 AND c.user_id = $2
`

type CountStudentsByClassroomParams struct {
	ClassroomID uuid.UUID `json:"classroom_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) CountStudentsByClassroom(ctx context.Context, arg CountStudentsByClassroomParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsByClassroom, arg.ClassroomID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsByUser = `-- name: CountStudentsByUser :one
SELECT COUNT(*) FROM students WHERE user_id = $1
`

func (q *Queries) CountStudentsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBonus = `-- name: CreateBonus :one

INSERT INTO bonuses (
    user_id, student_id, bonus_type_id, points
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, student_id, bonus_type_id, points, created_at, used_at
`

type CreateBonusParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StudentID   uuid.UUID `json:"student_id"`
	BonusTypeID uuid.UUID `json:"bonus_type_id"`
	Points      float64   `json:"points"`
}

// ==================== Bonus ====================
func (q *Queries) CreateBonus(ctx context.Context, arg CreateBonusParams) (Bonus, error) {
	row := q.db.QueryRow(ctx, createBonus,
		arg.UserID,
		arg.StudentID,
		arg.BonusTypeID,
		arg.Points,
	)
	var i Bonus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createBonusType = `-- name: CreateBonusType :one

INSERT INTO bonus_types (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateBonusTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// ==================== BonusType ====================
func (q *Queries) CreateBonusType(ctx context.Context, arg CreateBonusTypeParams) (BonusType, error) {
	row := q.db.QueryRow(ctx, createBonusType, arg.UserID, arg.Name)
	var i BonusType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClassroom = `-- name: CreateClassroom :one

INSERT INTO classrooms (
    user_id, name, year, main_teacher
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, name, year, main_teacher, created_at, updated_at
`

type CreateClassroomParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Name        string      `json:"name"`
	Year        pgtype.Text `json:"year"`
	MainTeacher pgtype.Text `json:"main_teacher"`
}

// ==================== Classroom ====================
func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, createClassroom,
		arg.UserID,
		arg.Name,
		arg.Year,
		arg.MainTeacher,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Year,
		&i.MainTeacher,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPenaltyType = `-- name: CreatePenaltyType :one

INSERT INTO penalty_types (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name, created_at, updated_at
`

type CreatePenaltyTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// ==================== PenaltyType ====================
func (q *Queries) CreatePenaltyType(ctx context.Context, arg CreatePenaltyTypeParams) (PenaltyType, error) {
	row := q.db.QueryRow(ctx, createPenaltyType, arg.UserID, arg.Name)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (
    user_id, token, user_agent, client_ip, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, token, user_agent, client_ip, revoked_at, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	UserAgent string    `json:"user_agent"`
	ClientIp  string    `json:"client_ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ==================== RefreshToken ====================
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.Token,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.ClientIp,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one

INSERT INTO students (
    user_id, first_name, last_name
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, first_name, last_name, created_at, updated_at
`

type CreateStudentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

// ==================== Student ====================
func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.UserID, arg.FirstName, arg.LastName)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email, first_name, last_name, password_hash
) VALUES (
    LOWER($1), $2, $3, $4
)
RETURNING id, email, first_name, last_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ==================== User ====================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBonusByUser = `-- name: DeleteBonusByUser :execrows
DELETE FROM bonuses
WHERE id = $1 AND user_id = $2
`

type DeleteBonusByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBonusByUser(ctx context.Context, arg DeleteBonusByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBonusByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBonusTypeByUser = `-- name: DeleteBonusTypeByUser :execrows
DELETE FROM bonus_types
WHERE id = $1 AND user_id = $2
`

type DeleteBonusTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBonusTypeByUser(ctx context.Context, arg DeleteBonusTypeByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBonusTypeByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteClassroomByUser = `-- name: DeleteClassroomByUser :execrows
DELETE FROM classrooms
WHERE id = $1 AND user_id = $2
`

type DeleteClassroomByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteClassroomByUser(ctx context.Context, arg DeleteClassroomByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClassroomByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePenaltyTypeByUser = `-- name: DeletePenaltyTypeByUser :execrows
DELETE FROM penalty_types
WHERE id = $1 AND user_id = $2
`

type DeletePenaltyTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePenaltyTypeByUser(ctx context.Context, arg DeletePenaltyTypeByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePenaltyTypeByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const deleteStudentByUser = `-- name: DeleteStudentByUser :execrows
DELETE FROM students
WHERE id = $1 AND user_id = $2
`

type DeleteStudentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStudentByUser(ctx context.Context, arg DeleteStudentByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBonusByUser = `-- name: GetBonusByUser :one
SELECT id, user_id, student_id, bonus_type_id, points, created_at, used_at
FROM bonuses
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetBonusByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBonusByUser(ctx context.Context, arg GetBonusByUserParams) (Bonus, error) {
	row := q.db.QueryRow(ctx, getBonusByUser, arg.ID, arg.UserID)
	var i Bonus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getBonusTypeByUser = `-- name: GetBonusTypeByUser :one
SELECT id, user_id, name, created_at, updated_at
FROM bonus_types
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetBonusTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBonusTypeByUser(ctx context.Context, arg GetBonusTypeByUserParams) (BonusType, error) {
	row := q.db.QueryRow(ctx, getBonusTypeByUser, arg.ID, arg.UserID)
	var i BonusType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassroomByUser = `-- name: GetClassroomByUser :one
SELECT id, user_id, name, year, main_teacher, created_at, updated_at
FROM classrooms
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetClassroomByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetClassroomByUser(ctx context.Context, arg GetClassroomByUserParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, getClassroomByUser, arg.ID, arg.UserID)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Year,
		&i.MainTeacher,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPenaltyTypeByUser = `-- name: GetPenaltyTypeByUser :one
SELECT id, user_id, name, created_at, updated_at
FROM penalty_types
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetPenaltyTypeByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPenaltyTypeByUser(ctx context.Context, arg GetPenaltyTypeByUserParams) (PenaltyType, error) {
	row := q.db.QueryRow(ctx, getPenaltyTypeByUser, arg.ID, arg.UserID)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, user_agent, client_ip, revoked_at, expires_at, created_at
FROM refresh_tokens
WHERE user_id = $1 AND token = $2 AND revoked_at IS NULL LIMIT 1
`

type GetRefreshTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, arg.UserID, arg.Token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.ClientIp,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByUser = `-- name: GetStudentByUser :one
SELECT id, user_id, first_name, last_name, created_at, updated_at
FROM students
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetStudentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetStudentByUser(ctx context.Context, arg GetStudentByUserParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUser, arg.ID, arg.UserID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialsByEmailForAuth = `-- name: GetUserCredentialsByEmailForAuth :one
SELECT id, email, password_hash FROM users WHERE email = LOWER($1) LIMIT 1
`

type GetUserCredentialsByEmailForAuthRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetUserCredentialsByEmailForAuth(ctx context.Context, email string) (GetUserCredentialsByEmailForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmailForAuth, email)
	var i GetUserCredentialsByEmailForAuthRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const listBonusTypesByUser = `-- name: ListBonusTypesByUser :many
SELECT id, user_id, name, created_at, updated_at
FROM bonus_types
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListBonusTypesByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListBonusTypesByUser(ctx context.Context, arg ListBonusTypesByUserParams) ([]BonusType, error) {
	rows, err := q.db.Query(ctx, listBonusTypesByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BonusType
	for rows.Next() {
		var i BonusType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusesByStudent = `-- name: ListBonusesByStudent :many
SELECT id, user_id, student_id, bonus_type_id, points, created_at, used_at
FROM bonuses
WHERE student_id = $1
  AND user_id = $2
  AND ($3::boolean IS NULL OR (used_at IS NOT NULL) = $3::boolean)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListBonusesByStudentParams struct {
	StudentID   uuid.UUID   `json:"student_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Used        pgtype.Bool `json:"used"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

func (q *Queries) ListBonusesByStudent(ctx context.Context, arg ListBonusesByStudentParams) ([]Bonus, error) {
	rows, err := q.db.Query(ctx, listBonusesByStudent,
		arg.StudentID,
		arg.UserID,
		arg.Used,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bonus
	for rows.Next() {
		var i Bonus
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.BonusTypeID,
			&i.Points,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusesByUser = `-- name: ListBonusesByUser :many
SELECT id, user_id, student_id, bonus_type_id, points, created_at, used_at
FROM bonuses
WHERE user_id = $1
  AND ($2::boolean IS NULL OR (used_at IS NOT NULL) = $2::boolean)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListBonusesByUserParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Used        pgtype.Bool `json:"used"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

func (q *Queries) ListBonusesByUser(ctx context.Context, arg ListBonusesByUserParams) ([]Bonus, error) {
	rows, err := q.db.Query(ctx, listBonusesByUser,
		arg.UserID,
		arg.Used,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bonus
	for rows.Next() {
		var i Bonus
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.BonusTypeID,
			&i.Points,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassroomsByStudent = `-- name: ListClassroomsByStudent :many
SELECT c.id, c.user_id, c.name, c.year, c.main_teacher, c.created_at, c.updated_at
FROM classrooms c
JOIN student_classrooms sc ON sc.classroom_id = c.id
JOIN students s ON s.id = sc.student_id
WHERE sc.student_id = $1 AND s.user_id = $2
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type ListClassroomsByStudentParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListClassroomsByStudent(ctx context.Context, arg ListClassroomsByStudentParams) ([]Classroom, error) {
	rows, err := q.db.Query(ctx, listClassroomsByStudent,
		arg.StudentID,
		arg.UserID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classroom
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Year,
			&i.MainTeacher,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassroomsByUser = `-- name: ListClassroomsByUser :many
SELECT id, user_id, name, year, main_teacher, created_at, updated_at
FROM classrooms
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListClassroomsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListClassroomsByUser(ctx context.Context, arg ListClassroomsByUserParams) ([]Classroom, error) {
	rows, err := q.db.Query(ctx, listClassroomsByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classroom
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Year,
			&i.MainTeacher,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPenaltyTypesByUser = `-- name: ListPenaltyTypesByUser :many
SELECT id, user_id, name, created_at, updated_at
FROM penalty_types
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListPenaltyTypesByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListPenaltyTypesByUser(ctx context.Context, arg ListPenaltyTypesByUserParams) ([]PenaltyType, error) {
	rows, err := q.db.Query(ctx, listPenaltyTypesByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyType
	for rows.Next() {
		var i PenaltyType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefreshTokensByUserId = `-- name: ListRefreshTokensByUserId :many
SELECT id, user_id, token, user_agent, client_ip, revoked_at, expires_at, created_at
FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRefreshTokensByUserId(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.UserAgent,
			&i.ClientIp,
			&i.RevokedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByClassroom = `-- name: ListStudentsByClassroom :many
SELECT s.id, s.user_id, s.first_name, s.last_name, s.created_at, s.updated_at
FROM students s
JOIN student_classrooms sc ON sc.student_id = s.id
JOIN classrooms c ON c.id = sc.classroom_id
WHERE sc.classroom_id = $1 AND c.user_id = $2
ORDER BY s.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStudentsByClassroomParams struct {
	ClassroomID uuid.UUID `json:"classroom_id"`
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListStudentsByClassroom(ctx context.Context, arg ListStudentsByClassroomParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByClassroom,
		arg.ClassroomID,
		arg.UserID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByUser = `-- name: ListStudentsByUser :many
SELECT id, user_id, first_name, last_name, created_at, updated_at
FROM students
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListStudentsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListStudentsByUser(ctx context.Context, arg ListStudentsByUserParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudentFromClassroom = `-- name: RemoveStudentFromClassroom :execrows
DELETE FROM student_classrooms
WHERE student_id = $1
  AND classroom_id = $2
  AND EXISTS (
    SELECT 1 FROM classrooms cl WHERE cl.id = $2 AND cl.user_id = $3
  )
`

type RemoveStudentFromClassroomParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveStudentFromClassroom(ctx context.Context, arg RemoveStudentFromClassroomParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeStudentFromClassroom, arg.StudentID, arg.ClassroomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token = $1
RETURNING id, user_id, token, revoked_at, expires_at
`

type RevokeRefreshTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt time.Time          `json:"expires_at"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (RevokeRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, token)
	var i RevokeRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateBonusTypeByUser = `-- name: UpdateBonusTypeByUser :one
UPDATE bonus_types
SET
    name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateBonusTypeByUserParams struct {
	Name   pgtype.Text `json:"name"`
	ID     uuid.UUID   `json:"id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateBonusTypeByUser(ctx context.Context, arg UpdateBonusTypeByUserParams) (BonusType, error) {
	row := q.db.QueryRow(ctx, updateBonusTypeByUser, arg.Name, arg.ID, arg.UserID)
	var i BonusType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClassroomByUser = `-- name: UpdateClassroomByUser :one
UPDATE classrooms
SET
    name = COALESCE($1, name),
    year = COALESCE($2, year),
    main_teacher = COALESCE($3, main_teacher),
    updated_at = NOW()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, name, year, main_teacher, created_at, updated_at
`

type UpdateClassroomByUserParams struct {
	Name        pgtype.Text `json:"name"`
	Year        pgtype.Text `json:"year"`
	MainTeacher pgtype.Text `json:"main_teacher"`
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateClassroomByUser(ctx context.Context, arg UpdateClassroomByUserParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, updateClassroomByUser,
		arg.Name,
		arg.Year,
		arg.MainTeacher,
		arg.ID,
		arg.UserID,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Year,
		&i.MainTeacher,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePenaltyTypeByUser = `-- name: UpdatePenaltyTypeByUser :one
UPDATE penalty_types
SET
    name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, created_at, updated_at
`

type UpdatePenaltyTypeByUserParams struct {
	Name   pgtype.Text `json:"name"`
	ID     uuid.UUID   `json:"id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdatePenaltyTypeByUser(ctx context.Context, arg UpdatePenaltyTypeByUserParams) (PenaltyType, error) {
	row := q.db.QueryRow(ctx, updatePenaltyTypeByUser, arg.Name, arg.ID, arg.UserID)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudentByUser = `-- name: UpdateStudentByUser :one
UPDATE students
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, first_name, last_name, created_at, updated_at
`

type UpdateStudentByUserParams struct {
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateStudentByUser(ctx context.Context, arg UpdateStudentByUserParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudentByUser,
		arg.FirstName,
		arg.LastName,
		arg.ID,
		arg.UserID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const useBonus = `-- name: UseBonus :one
UPDATE bonuses
SET used_at = NOW()
WHERE id = $1 AND user_id = $2 AND used_at IS NULL
RETURNING id, user_id, student_id, bonus_type_id, points, created_at, used_at
`

type UseBonusParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UseBonus(ctx context.Context, arg UseBonusParams) (Bonus, error) {
	row := q.db.QueryRow(ctx, useBonus, arg.ID, arg.UserID)
	var i Bonus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.BonusTypeID,
		&i.Points,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = LOWER($1) LIMIT 1
)
`

func (q *Queries) UserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
