// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ==================== StudentClassroom ====================
	AddStudentToClassroom(ctx context.Context, arg AddStudentToClassroomParams) (int64, error)
	CountBonusTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountBonusesByStudent(ctx context.Context, arg CountBonusesByStudentParams) (int64, error)
	CountBonusesByUser(ctx context.Context, arg CountBonusesByUserParams) (int64, error)
	CountClassroomsByStudent(ctx context.Context, arg CountClassroomsByStudentParams) (int64, error)
	CountClassroomsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPenaltiesByStudent(ctx context.Context, arg CountPenaltiesByStudentParams) (int64, error)
	CountPenaltiesByStudentAndType(ctx context.Context, arg CountPenaltiesByStudentAndTypeParams) (int64, error)
	CountPenaltiesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPenaltyTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPunishmentTypesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPunishmentsByStudent(ctx context.Context, arg CountPunishmentsByStudentParams) (int64, error)
	CountPunishmentsByUser(ctx context.Context, arg CountPunishmentsByUserParams) (int64, error)
	CountRulesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountStudentHistory(ctx context.Context, arg CountStudentHistoryParams) (int64, error)
	CountStudentsByClassroom(ctx context.Context, arg CountStudentsByClassroomParams) (int64, error)
	CountStudentsByUser(ctx context.Context, arg CountStudentsByUserParams) (int64, error)
	// ==================== Bonus ====================
	CreateBonus(ctx context.Context, arg CreateBonusParams) (CreateBonusRow, error)
	// ==================== BonusType ====================
	CreateBonusType(ctx context.Context, arg CreateBonusTypeParams) (BonusType, error)
	// ==================== Classroom ====================
	CreateClassroom(ctx context.Context, arg CreateClassroomParams) (CreateClassroomRow, error)
	// ==================== Penalty ====================
	CreatePenalty(ctx context.Context, arg CreatePenaltyParams) (CreatePenaltyRow, error)
	// ==================== PenaltyType ====================
	CreatePenaltyType(ctx context.Context, arg CreatePenaltyTypeParams) (PenaltyType, error)
	// ==================== Punishment ====================
	CreatePunishment(ctx context.Context, arg CreatePunishmentParams) (CreatePunishmentRow, error)
	CreatePunishmentFromRule(ctx context.Context, arg CreatePunishmentFromRuleParams) (CreatePunishmentFromRuleRow, error)
	// ==================== PunishmentType ====================
	CreatePunishmentType(ctx context.Context, arg CreatePunishmentTypeParams) (PunishmentType, error)
	// ==================== RefreshToken ====================
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// ==================== Rule ====================
	CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error)
	// ==================== Student ====================
	CreateStudent(ctx context.Context, arg CreateStudentParams) (CreateStudentRow, error)
	// ==================== User ====================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteBonusByUser(ctx context.Context, arg DeleteBonusByUserParams) (int64, error)
	DeleteBonusTypeByUser(ctx context.Context, arg DeleteBonusTypeByUserParams) (int64, error)
	DeleteClassroomByUser(ctx context.Context, arg DeleteClassroomByUserParams) (int64, error)
	DeletePenaltyByUser(ctx context.Context, arg DeletePenaltyByUserParams) (int64, error)
	DeletePenaltyTypeByUser(ctx context.Context, arg DeletePenaltyTypeByUserParams) (int64, error)
	DeletePunishmentByUser(ctx context.Context, arg DeletePunishmentByUserParams) (int64, error)
	DeletePunishmentTypeByUser(ctx context.Context, arg DeletePunishmentTypeByUserParams) (int64, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokensByUserId(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteRuleByUser(ctx context.Context, arg DeleteRuleByUserParams) (int64, error)
	DeleteStudentByUser(ctx context.Context, arg DeleteStudentByUserParams) (int64, error)
	GetBonusByUser(ctx context.Context, arg GetBonusByUserParams) (GetBonusByUserRow, error)
	GetBonusTypeByUser(ctx context.Context, arg GetBonusTypeByUserParams) (BonusType, error)
	GetClassroomByUser(ctx context.Context, arg GetClassroomByUserParams) (GetClassroomByUserRow, error)
	// ==================== Dashboard ====================
	GetDashboardKpis(ctx context.Context, arg GetDashboardKpisParams) (GetDashboardKpisRow, error)
	GetPenaltyByUser(ctx context.Context, arg GetPenaltyByUserParams) (GetPenaltyByUserRow, error)
	GetPenaltyTypeByUser(ctx context.Context, arg GetPenaltyTypeByUserParams) (PenaltyType, error)
	GetPunishmentByUser(ctx context.Context, arg GetPunishmentByUserParams) (GetPunishmentByUserRow, error)
	GetPunishmentTypeByUser(ctx context.Context, arg GetPunishmentTypeByUserParams) (PunishmentType, error)
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error)
	GetRuleByUser(ctx context.Context, arg GetRuleByUserParams) (GetRuleByUserRow, error)
	GetStudentByUser(ctx context.Context, arg GetStudentByUserParams) (GetStudentByUserRow, error)
	// ==================== StudentKpisHistory ====================
	GetStudentKpis(ctx context.Context, arg GetStudentKpisParams) (GetStudentKpisRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserCredentialsByEmailForAuth(ctx context.Context, email string) (GetUserCredentialsByEmailForAuthRow, error)
	ListActiveRulesByUserAndPenaltyType(ctx context.Context, arg ListActiveRulesByUserAndPenaltyTypeParams) ([]Rule, error)
	ListBonusTypesByUser(ctx context.Context, arg ListBonusTypesByUserParams) ([]BonusType, error)
	ListBonusesByStudent(ctx context.Context, arg ListBonusesByStudentParams) ([]ListBonusesByStudentRow, error)
	ListBonusesByUser(ctx context.Context, arg ListBonusesByUserParams) ([]ListBonusesByUserRow, error)
	ListClassroomRefsByStudentIDs(ctx context.Context, arg ListClassroomRefsByStudentIDsParams) ([]ListClassroomRefsByStudentIDsRow, error)
	ListClassroomsByStudent(ctx context.Context, arg ListClassroomsByStudentParams) ([]ListClassroomsByStudentRow, error)
	ListClassroomsByUser(ctx context.Context, arg ListClassroomsByUserParams) ([]ListClassroomsByUserRow, error)
	ListDashboardPendingPunishments(ctx context.Context, arg ListDashboardPendingPunishmentsParams) ([]ListDashboardPendingPunishmentsRow, error)
	ListDashboardRecentBonuses(ctx context.Context, arg ListDashboardRecentBonusesParams) ([]ListDashboardRecentBonusesRow, error)
	ListDashboardRecentPenalties(ctx context.Context, arg ListDashboardRecentPenaltiesParams) ([]ListDashboardRecentPenaltiesRow, error)
	ListPenaltiesByStudent(ctx context.Context, arg ListPenaltiesByStudentParams) ([]ListPenaltiesByStudentRow, error)
	ListPenaltiesByUser(ctx context.Context, arg ListPenaltiesByUserParams) ([]ListPenaltiesByUserRow, error)
	ListPenaltyTypesByUser(ctx context.Context, arg ListPenaltyTypesByUserParams) ([]PenaltyType, error)
	ListPunishmentTypesByUser(ctx context.Context, arg ListPunishmentTypesByUserParams) ([]PunishmentType, error)
	ListPunishmentsByStudent(ctx context.Context, arg ListPunishmentsByStudentParams) ([]ListPunishmentsByStudentRow, error)
	ListPunishmentsByUser(ctx context.Context, arg ListPunishmentsByUserParams) ([]ListPunishmentsByUserRow, error)
	ListRefreshTokensByUserId(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	ListRulesByUser(ctx context.Context, arg ListRulesByUserParams) ([]ListRulesByUserRow, error)
	ListStudentHistory(ctx context.Context, arg ListStudentHistoryParams) ([]ListStudentHistoryRow, error)
	ListStudentsByClassroom(ctx context.Context, arg ListStudentsByClassroomParams) ([]ListStudentsByClassroomRow, error)
	ListStudentsByUser(ctx context.Context, arg ListStudentsByUserParams) ([]ListStudentsByUserRow, error)
	ListStudentsPreviewByClassroomIDs(ctx context.Context, arg ListStudentsPreviewByClassroomIDsParams) ([]ListStudentsPreviewByClassroomIDsRow, error)
	RemoveStudentFromClassroom(ctx context.Context, arg RemoveStudentFromClassroomParams) (int64, error)
	ResolvePunishment(ctx context.Context, arg ResolvePunishmentParams) (ResolvePunishmentRow, error)
	RevokeRefreshToken(ctx context.Context, token string) (RevokeRefreshTokenRow, error)
	UpdateBonusTypeByUser(ctx context.Context, arg UpdateBonusTypeByUserParams) (BonusType, error)
	UpdateClassroomByUser(ctx context.Context, arg UpdateClassroomByUserParams) (UpdateClassroomByUserRow, error)
	UpdatePenaltyTypeByUser(ctx context.Context, arg UpdatePenaltyTypeByUserParams) (PenaltyType, error)
	UpdatePunishmentTypeByUser(ctx context.Context, arg UpdatePunishmentTypeByUserParams) (PunishmentType, error)
	UpdateRuleByUser(ctx context.Context, arg UpdateRuleByUserParams) (UpdateRuleByUserRow, error)
	UpdateStudentByUser(ctx context.Context, arg UpdateStudentByUserParams) (UpdateStudentByUserRow, error)
	UseBonus(ctx context.Context, arg UseBonusParams) (UseBonusRow, error)
	UserEmailExists(ctx context.Context, email string) (bool, error)
}

var _ Querier = (*Queries)(nil)
