// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudentsByUser = `-- name: CountStudentsByUser :one
SELECT COUNT(*) FROM students WHERE user_id = $1
`

func (q *Queries) CountStudentsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token, user_agent, client_ip, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, token, user_agent, client_ip, revoked_at, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	UserAgent string    `json:"user_agent"`
	ClientIp  string    `json:"client_ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.Token,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.ClientIp,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    user_id, first_name, last_name
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, first_name, last_name, created_at, updated_at
`

type CreateStudentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.UserID, arg.FirstName, arg.LastName)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, first_name, last_name, password_hash
) VALUES (
    LOWER($1), $2, $3, $4
)
RETURNING id, email, first_name, last_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const deleteStudentByUser = `-- name: DeleteStudentByUser :exec
DELETE FROM students
WHERE id = $1 AND user_id = $2
`

type DeleteStudentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStudentByUser(ctx context.Context, arg DeleteStudentByUserParams) error {
	_, err := q.db.Exec(ctx, deleteStudentByUser, arg.ID, arg.UserID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, user_agent, client_ip, revoked_at, expires_at, created_at
FROM refresh_tokens
WHERE user_id = $1 AND token = $2 AND revoked_at IS NULL LIMIT 1
`

type GetRefreshTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, arg.UserID, arg.Token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.ClientIp,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByUser = `-- name: GetStudentByUser :one
SELECT id, user_id, first_name, last_name, created_at, updated_at
FROM students
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetStudentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetStudentByUser(ctx context.Context, arg GetStudentByUserParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUser, arg.ID, arg.UserID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialsByEmailForAuth = `-- name: GetUserCredentialsByEmailForAuth :one
SELECT id, email, password_hash FROM users WHERE email = LOWER($1) LIMIT 1
`

type GetUserCredentialsByEmailForAuthRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetUserCredentialsByEmailForAuth(ctx context.Context, email string) (GetUserCredentialsByEmailForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmailForAuth, email)
	var i GetUserCredentialsByEmailForAuthRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const listRefreshTokensByUserId = `-- name: ListRefreshTokensByUserId :many
SELECT id, user_id, token, user_agent, client_ip, revoked_at, expires_at, created_at
FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRefreshTokensByUserId(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.UserAgent,
			&i.ClientIp,
			&i.RevokedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByUser = `-- name: ListStudentsByUser :many
SELECT id, user_id, first_name, last_name, created_at, updated_at
FROM students
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListStudentsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListStudentsByUser(ctx context.Context, arg ListStudentsByUserParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token = $1
RETURNING id, user_id, token, revoked_at, expires_at
`

type RevokeRefreshTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt time.Time          `json:"expires_at"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (RevokeRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, token)
	var i RevokeRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateStudentByUser = `-- name: UpdateStudentByUser :one
UPDATE students
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, first_name, last_name, created_at, updated_at
`

type UpdateStudentByUserParams struct {
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateStudentByUser(ctx context.Context, arg UpdateStudentByUserParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudentByUser,
		arg.FirstName,
		arg.LastName,
		arg.ID,
		arg.UserID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = LOWER($1) LIMIT 1
)
`

func (q *Queries) UserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
