// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRulesByUser = `-- name: CountRulesByUser :one
SELECT COUNT(*) FROM rules WHERE user_id = $1
`

func (q *Queries) CountRulesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRulesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRule = `-- name: CreateRule :one

INSERT INTO rules (
    user_id, name, resulting_punishment_type_id, penalty_type_id, threshold, mode, is_active, due_at_after_days, due_at_mode, due_at_after_lessons
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING
    id, user_id, name, resulting_punishment_type_id, penalty_type_id, threshold, mode, is_active, created_at, updated_at, due_at_after_days, due_at_mode, due_at_after_lessons,
    (SELECT name FROM penalty_types WHERE penalty_types.id = rules.penalty_type_id AND penalty_types.user_id = rules.user_id) AS penalty_type_name,
    (SELECT name FROM punishment_types WHERE punishment_types.id = rules.resulting_punishment_type_id AND punishment_types.user_id = rules.user_id) AS resulting_punishment_type_name
`

type CreateRuleParams struct {
	UserID                    uuid.UUID `json:"user_id"`
	Name                      string    `json:"name"`
	ResultingPunishmentTypeID uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID             uuid.UUID `json:"penalty_type_id"`
	Threshold                 int32     `json:"threshold"`
	Mode                      string    `json:"mode"`
	IsActive                  bool      `json:"is_active"`
	DueAtAfterDays            int32     `json:"due_at_after_days"`
	DueAtMode                 string    `json:"due_at_mode"`
	DueAtAfterLessons         *int32    `json:"due_at_after_lessons"`
}

type CreateRuleRow struct {
	ID                          uuid.UUID `json:"id"`
	UserID                      uuid.UUID `json:"user_id"`
	Name                        string    `json:"name"`
	ResultingPunishmentTypeID   uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID               uuid.UUID `json:"penalty_type_id"`
	Threshold                   int32     `json:"threshold"`
	Mode                        string    `json:"mode"`
	IsActive                    bool      `json:"is_active"`
	CreatedAt                   time.Time `json:"created_at"`
	UpdatedAt                   time.Time `json:"updated_at"`
	DueAtAfterDays              int32     `json:"due_at_after_days"`
	DueAtMode                   string    `json:"due_at_mode"`
	DueAtAfterLessons           *int32    `json:"due_at_after_lessons"`
	PenaltyTypeName             string    `json:"penalty_type_name"`
	ResultingPunishmentTypeName string    `json:"resulting_punishment_type_name"`
}

// ==================== Rule ====================
func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.UserID,
		arg.Name,
		arg.ResultingPunishmentTypeID,
		arg.PenaltyTypeID,
		arg.Threshold,
		arg.Mode,
		arg.IsActive,
		arg.DueAtAfterDays,
		arg.DueAtMode,
		arg.DueAtAfterLessons,
	)
	var i CreateRuleRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ResultingPunishmentTypeID,
		&i.PenaltyTypeID,
		&i.Threshold,
		&i.Mode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAtAfterDays,
		&i.DueAtMode,
		&i.DueAtAfterLessons,
		&i.PenaltyTypeName,
		&i.ResultingPunishmentTypeName,
	)
	return i, err
}

const deleteRuleByUser = `-- name: DeleteRuleByUser :execrows
DELETE FROM rules
WHERE id = $1 AND user_id = $2
`

type DeleteRuleByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRuleByUser(ctx context.Context, arg DeleteRuleByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuleByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRuleByUser = `-- name: GetRuleByUser :one
SELECT
    r.id, r.user_id, r.name, r.resulting_punishment_type_id, r.penalty_type_id, r.threshold, r.mode, r.is_active, r.created_at, r.updated_at, r.due_at_after_days, r.due_at_mode, r.due_at_after_lessons,
    pt.name AS penalty_type_name,
    put.name AS resulting_punishment_type_name
FROM rules r
JOIN penalty_types pt ON pt.id = r.penalty_type_id AND pt.user_id = r.user_id
JOIN punishment_types put ON put.id = r.resulting_punishment_type_id AND put.user_id = r.user_id
WHERE r.id = $1 AND r.user_id = $2 LIMIT 1
`

type GetRuleByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetRuleByUserRow struct {
	ID                          uuid.UUID `json:"id"`
	UserID                      uuid.UUID `json:"user_id"`
	Name                        string    `json:"name"`
	ResultingPunishmentTypeID   uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID               uuid.UUID `json:"penalty_type_id"`
	Threshold                   int32     `json:"threshold"`
	Mode                        string    `json:"mode"`
	IsActive                    bool      `json:"is_active"`
	CreatedAt                   time.Time `json:"created_at"`
	UpdatedAt                   time.Time `json:"updated_at"`
	DueAtAfterDays              int32     `json:"due_at_after_days"`
	DueAtMode                   string    `json:"due_at_mode"`
	DueAtAfterLessons           *int32    `json:"due_at_after_lessons"`
	PenaltyTypeName             string    `json:"penalty_type_name"`
	ResultingPunishmentTypeName string    `json:"resulting_punishment_type_name"`
}

func (q *Queries) GetRuleByUser(ctx context.Context, arg GetRuleByUserParams) (GetRuleByUserRow, error) {
	row := q.db.QueryRow(ctx, getRuleByUser, arg.ID, arg.UserID)
	var i GetRuleByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ResultingPunishmentTypeID,
		&i.PenaltyTypeID,
		&i.Threshold,
		&i.Mode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAtAfterDays,
		&i.DueAtMode,
		&i.DueAtAfterLessons,
		&i.PenaltyTypeName,
		&i.ResultingPunishmentTypeName,
	)
	return i, err
}

const listActiveRulesByUserAndPenaltyType = `-- name: ListActiveRulesByUserAndPenaltyType :many
SELECT id, user_id, name, resulting_punishment_type_id, penalty_type_id, threshold, mode, is_active, created_at, updated_at, due_at_after_days, due_at_mode, due_at_after_lessons
FROM rules
WHERE user_id = $1
  AND penalty_type_id = $2
  AND is_active = TRUE
ORDER BY created_at DESC
`

type ListActiveRulesByUserAndPenaltyTypeParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PenaltyTypeID uuid.UUID `json:"penalty_type_id"`
}

func (q *Queries) ListActiveRulesByUserAndPenaltyType(ctx context.Context, arg ListActiveRulesByUserAndPenaltyTypeParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listActiveRulesByUserAndPenaltyType, arg.UserID, arg.PenaltyTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ResultingPunishmentTypeID,
			&i.PenaltyTypeID,
			&i.Threshold,
			&i.Mode,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueAtAfterDays,
			&i.DueAtMode,
			&i.DueAtAfterLessons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByUser = `-- name: ListRulesByUser :many
SELECT
    r.id, r.user_id, r.name, r.resulting_punishment_type_id, r.penalty_type_id, r.threshold, r.mode, r.is_active, r.created_at, r.updated_at, r.due_at_after_days, r.due_at_mode, r.due_at_after_lessons,
    pt.name AS penalty_type_name,
    put.name AS resulting_punishment_type_name
FROM rules r
JOIN penalty_types pt ON pt.id = r.penalty_type_id AND pt.user_id = r.user_id
JOIN punishment_types put ON put.id = r.resulting_punishment_type_id AND put.user_id = r.user_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
LIMIT $3 OFFSET $2
`

type ListRulesByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListRulesByUserRow struct {
	ID                          uuid.UUID `json:"id"`
	UserID                      uuid.UUID `json:"user_id"`
	Name                        string    `json:"name"`
	ResultingPunishmentTypeID   uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID               uuid.UUID `json:"penalty_type_id"`
	Threshold                   int32     `json:"threshold"`
	Mode                        string    `json:"mode"`
	IsActive                    bool      `json:"is_active"`
	CreatedAt                   time.Time `json:"created_at"`
	UpdatedAt                   time.Time `json:"updated_at"`
	DueAtAfterDays              int32     `json:"due_at_after_days"`
	DueAtMode                   string    `json:"due_at_mode"`
	DueAtAfterLessons           *int32    `json:"due_at_after_lessons"`
	PenaltyTypeName             string    `json:"penalty_type_name"`
	ResultingPunishmentTypeName string    `json:"resulting_punishment_type_name"`
}

func (q *Queries) ListRulesByUser(ctx context.Context, arg ListRulesByUserParams) ([]ListRulesByUserRow, error) {
	rows, err := q.db.Query(ctx, listRulesByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesByUserRow
	for rows.Next() {
		var i ListRulesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ResultingPunishmentTypeID,
			&i.PenaltyTypeID,
			&i.Threshold,
			&i.Mode,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueAtAfterDays,
			&i.DueAtMode,
			&i.DueAtAfterLessons,
			&i.PenaltyTypeName,
			&i.ResultingPunishmentTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuleByUser = `-- name: UpdateRuleByUser :one
UPDATE rules
SET
    name = $1,
    resulting_punishment_type_id = $2,
    penalty_type_id = $3,
    threshold = $4,
    mode = $5,
    is_active = $6,
    due_at_after_days = $7,
    due_at_mode = $8,
    due_at_after_lessons = $9,
    updated_at = NOW()
WHERE rules.id = $10 AND rules.user_id = $11
RETURNING
    rules.id, rules.user_id, rules.name, rules.resulting_punishment_type_id, rules.penalty_type_id, rules.threshold, rules.mode, rules.is_active, rules.created_at, rules.updated_at, rules.due_at_after_days, rules.due_at_mode, rules.due_at_after_lessons,
    (SELECT name FROM penalty_types WHERE penalty_types.id = rules.penalty_type_id AND penalty_types.user_id = rules.user_id) AS penalty_type_name,
    (SELECT name FROM punishment_types WHERE punishment_types.id = rules.resulting_punishment_type_id AND punishment_types.user_id = rules.user_id) AS resulting_punishment_type_name
`

type UpdateRuleByUserParams struct {
	Name                      string    `json:"name"`
	ResultingPunishmentTypeID uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID             uuid.UUID `json:"penalty_type_id"`
	Threshold                 int32     `json:"threshold"`
	Mode                      string    `json:"mode"`
	IsActive                  bool      `json:"is_active"`
	DueAtAfterDays            int32     `json:"due_at_after_days"`
	DueAtMode                 string    `json:"due_at_mode"`
	DueAtAfterLessons         *int32    `json:"due_at_after_lessons"`
	ID                        uuid.UUID `json:"id"`
	UserID                    uuid.UUID `json:"user_id"`
}

type UpdateRuleByUserRow struct {
	ID                          uuid.UUID `json:"id"`
	UserID                      uuid.UUID `json:"user_id"`
	Name                        string    `json:"name"`
	ResultingPunishmentTypeID   uuid.UUID `json:"resulting_punishment_type_id"`
	PenaltyTypeID               uuid.UUID `json:"penalty_type_id"`
	Threshold                   int32     `json:"threshold"`
	Mode                        string    `json:"mode"`
	IsActive                    bool      `json:"is_active"`
	CreatedAt                   time.Time `json:"created_at"`
	UpdatedAt                   time.Time `json:"updated_at"`
	DueAtAfterDays              int32     `json:"due_at_after_days"`
	DueAtMode                   string    `json:"due_at_mode"`
	DueAtAfterLessons           *int32    `json:"due_at_after_lessons"`
	PenaltyTypeName             string    `json:"penalty_type_name"`
	ResultingPunishmentTypeName string    `json:"resulting_punishment_type_name"`
}

func (q *Queries) UpdateRuleByUser(ctx context.Context, arg UpdateRuleByUserParams) (UpdateRuleByUserRow, error) {
	row := q.db.QueryRow(ctx, updateRuleByUser,
		arg.Name,
		arg.ResultingPunishmentTypeID,
		arg.PenaltyTypeID,
		arg.Threshold,
		arg.Mode,
		arg.IsActive,
		arg.DueAtAfterDays,
		arg.DueAtMode,
		arg.DueAtAfterLessons,
		arg.ID,
		arg.UserID,
	)
	var i UpdateRuleByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ResultingPunishmentTypeID,
		&i.PenaltyTypeID,
		&i.Threshold,
		&i.Mode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAtAfterDays,
		&i.DueAtMode,
		&i.DueAtAfterLessons,
		&i.PenaltyTypeName,
		&i.ResultingPunishmentTypeName,
	)
	return i, err
}
