// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_exceptions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countScheduleExceptionOverlaps = `-- name: CountScheduleExceptionOverlaps :one
SELECT COUNT(*)
FROM schedule_exceptions se
WHERE se.user_id = $1
  AND (
    $2::uuid IS NULL
    OR se.id <> $2::uuid
  )
  AND daterange(se.start_date, se.end_date, '[]')
      && daterange($3::date, $4::date, '[]')
`

type CountScheduleExceptionOverlapsParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	ExcludedID *uuid.UUID `json:"excluded_id"`
	StartDate  time.Time  `json:"start_date"`
	EndDate    time.Time  `json:"end_date"`
}

func (q *Queries) CountScheduleExceptionOverlaps(ctx context.Context, arg CountScheduleExceptionOverlapsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduleExceptionOverlaps,
		arg.UserID,
		arg.ExcludedID,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduleException = `-- name: CreateScheduleException :one

INSERT INTO schedule_exceptions (
    user_id, exception_type, start_date, end_date
) VALUES (
    $1, $2, $3, $4
)
RETURNING
    id,
    user_id,
    exception_type AS type,
    start_date,
    end_date,
    created_at,
    updated_at
`

type CreateScheduleExceptionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ExceptionType string    `json:"exception_type"`
	StartDate     time.Time `json:"start_date"`
	EndDate       time.Time `json:"end_date"`
}

type CreateScheduleExceptionRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ==================== ScheduleException ====================
func (q *Queries) CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (CreateScheduleExceptionRow, error) {
	row := q.db.QueryRow(ctx, createScheduleException,
		arg.UserID,
		arg.ExceptionType,
		arg.StartDate,
		arg.EndDate,
	)
	var i CreateScheduleExceptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduleExceptionByUser = `-- name: DeleteScheduleExceptionByUser :execrows
DELETE FROM schedule_exceptions
WHERE id = $1 AND user_id = $2
`

type DeleteScheduleExceptionByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteScheduleExceptionByUser(ctx context.Context, arg DeleteScheduleExceptionByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleExceptionByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduleExceptionByUser = `-- name: GetScheduleExceptionByUser :one
SELECT
    id,
    user_id,
    exception_type AS type,
    start_date,
    end_date,
    created_at,
    updated_at
FROM schedule_exceptions
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetScheduleExceptionByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetScheduleExceptionByUserRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetScheduleExceptionByUser(ctx context.Context, arg GetScheduleExceptionByUserParams) (GetScheduleExceptionByUserRow, error) {
	row := q.db.QueryRow(ctx, getScheduleExceptionByUser, arg.ID, arg.UserID)
	var i GetScheduleExceptionByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduleExceptionsByUser = `-- name: ListScheduleExceptionsByUser :many
SELECT
    id,
    user_id,
    exception_type AS type,
    start_date,
    end_date,
    created_at,
    updated_at
FROM schedule_exceptions
WHERE user_id = $1
ORDER BY start_date ASC, end_date ASC, id ASC
`

type ListScheduleExceptionsByUserRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListScheduleExceptionsByUser(ctx context.Context, userID uuid.UUID) ([]ListScheduleExceptionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleExceptionsByUserRow
	for rows.Next() {
		var i ListScheduleExceptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleExceptionByUser = `-- name: UpdateScheduleExceptionByUser :one
UPDATE schedule_exceptions
SET
    exception_type = COALESCE($1, exception_type),
    start_date = COALESCE($2, start_date),
    end_date = COALESCE($3, end_date),
    updated_at = NOW()
WHERE id = $4 AND user_id = $5
RETURNING
    id,
    user_id,
    exception_type AS type,
    start_date,
    end_date,
    created_at,
    updated_at
`

type UpdateScheduleExceptionByUserParams struct {
	ExceptionType *string    `json:"exception_type"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
}

type UpdateScheduleExceptionByUserRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateScheduleExceptionByUser(ctx context.Context, arg UpdateScheduleExceptionByUserParams) (UpdateScheduleExceptionByUserRow, error) {
	row := q.db.QueryRow(ctx, updateScheduleExceptionByUser,
		arg.ExceptionType,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
		arg.UserID,
	)
	var i UpdateScheduleExceptionByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
