// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_slots.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countClassroomsByIDsAndUser = `-- name: CountClassroomsByIDsAndUser :one
SELECT COUNT(*)
FROM classrooms
WHERE user_id = $1
  AND id = ANY($2::uuid[])
`

type CountClassroomsByIDsAndUserParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	ClassroomIds []uuid.UUID `json:"classroom_ids"`
}

func (q *Queries) CountClassroomsByIDsAndUser(ctx context.Context, arg CountClassroomsByIDsAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClassroomsByIDsAndUser, arg.UserID, arg.ClassroomIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduleSlotConflicts = `-- name: CountScheduleSlotConflicts :one
SELECT COUNT(*)
FROM schedule_slots s
WHERE s.user_id = $1
  AND s.weekday = $2
  AND (
    $3::uuid IS NULL
    OR s.id <> $3::uuid
  )
  AND $4::time < s.end_time::time
  AND s.start_time::time < $5::time
  AND (
    s.week_pattern = 'every_week'
    OR $6::text = 'every_week'
    OR s.week_pattern = $6::text
  )
`

type CountScheduleSlotConflictsParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Weekday     int32       `json:"weekday"`
	ExcludedID  *uuid.UUID  `json:"excluded_id"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	WeekPattern string      `json:"week_pattern"`
}

func (q *Queries) CountScheduleSlotConflicts(ctx context.Context, arg CountScheduleSlotConflictsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduleSlotConflicts,
		arg.UserID,
		arg.Weekday,
		arg.ExcludedID,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduleSlot = `-- name: CreateScheduleSlot :one

INSERT INTO schedule_slots (
    user_id, weekday, start_time, end_time, week_pattern
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id, user_id, weekday, start_time, end_time, week_pattern, created_at, updated_at
`

type CreateScheduleSlotParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Weekday     int32     `json:"weekday"`
	StartTime   string    `json:"start_time"`
	EndTime     string    `json:"end_time"`
	WeekPattern string    `json:"week_pattern"`
}

// ==================== ScheduleSlot ====================
func (q *Queries) CreateScheduleSlot(ctx context.Context, arg CreateScheduleSlotParams) (ScheduleSlot, error) {
	row := q.db.QueryRow(ctx, createScheduleSlot,
		arg.UserID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
	)
	var i ScheduleSlot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.WeekPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduleSlotClassroomRelation = `-- name: CreateScheduleSlotClassroomRelation :execrows
INSERT INTO schedule_slot_classrooms (
    schedule_slot_id, classroom_id
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
`

type CreateScheduleSlotClassroomRelationParams struct {
	ScheduleSlotID uuid.UUID `json:"schedule_slot_id"`
	ClassroomID    uuid.UUID `json:"classroom_id"`
}

func (q *Queries) CreateScheduleSlotClassroomRelation(ctx context.Context, arg CreateScheduleSlotClassroomRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createScheduleSlotClassroomRelation, arg.ScheduleSlotID, arg.ClassroomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanScheduleSlotsByUser = `-- name: DeleteOrphanScheduleSlotsByUser :execrows
DELETE FROM schedule_slots s
WHERE s.user_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM schedule_slot_classrooms ssc
    WHERE ssc.schedule_slot_id = s.id
  )
`

func (q *Queries) DeleteOrphanScheduleSlotsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanScheduleSlotsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleSlotByUser = `-- name: DeleteScheduleSlotByUser :execrows
DELETE FROM schedule_slots
WHERE id = $1 AND user_id = $2
`

type DeleteScheduleSlotByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteScheduleSlotByUser(ctx context.Context, arg DeleteScheduleSlotByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleSlotByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleSlotClassroomRelationsBySlot = `-- name: DeleteScheduleSlotClassroomRelationsBySlot :execrows
DELETE FROM schedule_slot_classrooms
WHERE schedule_slot_id = $1
`

func (q *Queries) DeleteScheduleSlotClassroomRelationsBySlot(ctx context.Context, scheduleSlotID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleSlotClassroomRelationsBySlot, scheduleSlotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduleSlotByUser = `-- name: GetScheduleSlotByUser :one
SELECT
    id, user_id, weekday, start_time, end_time, week_pattern, created_at, updated_at
FROM schedule_slots
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetScheduleSlotByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetScheduleSlotByUser(ctx context.Context, arg GetScheduleSlotByUserParams) (ScheduleSlot, error) {
	row := q.db.QueryRow(ctx, getScheduleSlotByUser, arg.ID, arg.UserID)
	var i ScheduleSlot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.WeekPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduleSlotClassroomRefsBySlotIDs = `-- name: ListScheduleSlotClassroomRefsBySlotIDs :many
SELECT
    ssc.schedule_slot_id,
    c.id AS classroom_id,
    c.name AS classroom_name
FROM schedule_slot_classrooms ssc
JOIN schedule_slots s ON s.id = ssc.schedule_slot_id
JOIN classrooms c ON c.id = ssc.classroom_id
WHERE s.user_id = $1
  AND ssc.schedule_slot_id = ANY($2::uuid[])
ORDER BY ssc.schedule_slot_id ASC, c.name ASC, c.id ASC
`

type ListScheduleSlotClassroomRefsBySlotIDsParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	ScheduleSlotIds []uuid.UUID `json:"schedule_slot_ids"`
}

type ListScheduleSlotClassroomRefsBySlotIDsRow struct {
	ScheduleSlotID uuid.UUID `json:"schedule_slot_id"`
	ClassroomID    uuid.UUID `json:"classroom_id"`
	ClassroomName  string    `json:"classroom_name"`
}

func (q *Queries) ListScheduleSlotClassroomRefsBySlotIDs(ctx context.Context, arg ListScheduleSlotClassroomRefsBySlotIDsParams) ([]ListScheduleSlotClassroomRefsBySlotIDsRow, error) {
	rows, err := q.db.Query(ctx, listScheduleSlotClassroomRefsBySlotIDs, arg.UserID, arg.ScheduleSlotIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleSlotClassroomRefsBySlotIDsRow
	for rows.Next() {
		var i ListScheduleSlotClassroomRefsBySlotIDsRow
		if err := rows.Scan(&i.ScheduleSlotID, &i.ClassroomID, &i.ClassroomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleSlotsByClassroom = `-- name: ListScheduleSlotsByClassroom :many
SELECT
    s.id, s.user_id, s.weekday, s.start_time, s.end_time, s.week_pattern, s.created_at, s.updated_at
FROM schedule_slots s
JOIN schedule_slot_classrooms ssc ON ssc.schedule_slot_id = s.id
WHERE s.user_id = $1
  AND ssc.classroom_id = $2
ORDER BY s.weekday ASC, s.start_time ASC, s.id ASC
`

type ListScheduleSlotsByClassroomParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
}

func (q *Queries) ListScheduleSlotsByClassroom(ctx context.Context, arg ListScheduleSlotsByClassroomParams) ([]ScheduleSlot, error) {
	rows, err := q.db.Query(ctx, listScheduleSlotsByClassroom, arg.UserID, arg.ClassroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleSlot
	for rows.Next() {
		var i ScheduleSlot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.WeekPattern,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleSlotsByUser = `-- name: ListScheduleSlotsByUser :many
SELECT
    id, user_id, weekday, start_time, end_time, week_pattern, created_at, updated_at
FROM schedule_slots
WHERE user_id = $1
ORDER BY weekday ASC, start_time ASC, id ASC
`

func (q *Queries) ListScheduleSlotsByUser(ctx context.Context, userID uuid.UUID) ([]ScheduleSlot, error) {
	rows, err := q.db.Query(ctx, listScheduleSlotsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleSlot
	for rows.Next() {
		var i ScheduleSlot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.WeekPattern,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleSlotByUser = `-- name: UpdateScheduleSlotByUser :one
UPDATE schedule_slots
SET
    weekday = COALESCE($1, weekday),
    start_time = COALESCE($2, start_time),
    end_time = COALESCE($3, end_time),
    week_pattern = COALESCE($4, week_pattern),
    updated_at = NOW()
WHERE id = $5 AND user_id = $6
RETURNING
    id, user_id, weekday, start_time, end_time, week_pattern, created_at, updated_at
`

type UpdateScheduleSlotByUserParams struct {
	Weekday     *int32    `json:"weekday"`
	StartTime   *string   `json:"start_time"`
	EndTime     *string   `json:"end_time"`
	WeekPattern *string   `json:"week_pattern"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateScheduleSlotByUser(ctx context.Context, arg UpdateScheduleSlotByUserParams) (ScheduleSlot, error) {
	row := q.db.QueryRow(ctx, updateScheduleSlotByUser,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
		arg.ID,
		arg.UserID,
	)
	var i ScheduleSlot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.WeekPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
