// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student_kpis_history.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStudentHistory = `-- name: CountStudentHistory :one
SELECT (
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        WHERE p.student_id = $1
          AND p.user_id = $2
    ), 0)
    +
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = $1
          AND p.user_id = $2
    ), 0)
    +
    COALESCE((
        SELECT COUNT(*)
        FROM bonuses b
        WHERE b.student_id = $1
          AND b.user_id = $2
    ), 0)
)::bigint
`

type CountStudentHistoryParams struct {
	StudentID uuid.UUID `json:"student_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CountStudentHistory(ctx context.Context, arg CountStudentHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentHistory, arg.StudentID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getStudentKpis = `-- name: GetStudentKpis :one

SELECT
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = $1
          AND b.user_id = $2
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = $1
          AND b.user_id = $2
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM bonuses b
        WHERE b.student_id = $1
          AND b.user_id = $2
          AND b.used_at IS NULL
    ), 0)::bigint AS active_bonus_count,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = $1
          AND p.user_id = $2
    ), 0)::bigint AS penalty_count,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = $1
          AND p.user_id = $2
    ), 0)::bigint AS total_penalty_count,
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        WHERE p.student_id = $1
          AND p.user_id = $2
    ), 0)::bigint AS total_punishment_count,
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        WHERE p.student_id = $1
          AND p.user_id = $2
          AND p.resolved_at IS NULL
          AND p.due_at < NOW()
    ), 0)::bigint AS overdue_punishment_count,
    COALESCE((
        SELECT COUNT(*)
        FROM punishments p
        WHERE p.student_id = $1
          AND p.user_id = $2
          AND p.resolved_at IS NULL
    ), 0)::bigint AS pending_punishment_count
`

type GetStudentKpisParams struct {
	StudentID uuid.UUID `json:"student_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetStudentKpisRow struct {
	AvailableBonusPoints   float64 `json:"available_bonus_points"`
	TotalBonusPoints       float64 `json:"total_bonus_points"`
	ActiveBonusCount       int64   `json:"active_bonus_count"`
	PenaltyCount           int64   `json:"penalty_count"`
	TotalPenaltyCount      int64   `json:"total_penalty_count"`
	TotalPunishmentCount   int64   `json:"total_punishment_count"`
	OverduePunishmentCount int64   `json:"overdue_punishment_count"`
	PendingPunishmentCount int64   `json:"pending_punishment_count"`
}

// ==================== StudentKpisHistory ====================
func (q *Queries) GetStudentKpis(ctx context.Context, arg GetStudentKpisParams) (GetStudentKpisRow, error) {
	row := q.db.QueryRow(ctx, getStudentKpis, arg.StudentID, arg.UserID)
	var i GetStudentKpisRow
	err := row.Scan(
		&i.AvailableBonusPoints,
		&i.TotalBonusPoints,
		&i.ActiveBonusCount,
		&i.PenaltyCount,
		&i.TotalPenaltyCount,
		&i.TotalPunishmentCount,
		&i.OverduePunishmentCount,
		&i.PendingPunishmentCount,
	)
	return i, err
}

const listStudentHistory = `-- name: ListStudentHistory :many
SELECT
    history.type,
    history.id,
    history.created_at,
    history.occurred_at,
    history.evaluation_label,
    history.penalty_type_id,
    history.penalty_type_name,
    history.bonus_type_id,
    history.bonus_type_name,
    history.points,
    history.used_at,
    history.punishment_type_id,
    history.punishment_type_name,
    history.triggering_rule_id,
    history.triggering_rule_name,
    history.automated,
    history.due_at,
    history.resolved_at
FROM (
    SELECT
        'punishment'::text AS type,
        p.id,
        p.created_at,
        p.occurred_at,
        p.evaluation_label,
        NULL::uuid AS penalty_type_id,
        NULL::text AS penalty_type_name,
        NULL::uuid AS bonus_type_id,
        NULL::text AS bonus_type_name,
        NULL::double precision AS points,
        NULL::timestamptz AS used_at,
        CASE WHEN TRUE THEN p.punishment_type_id ELSE NULL::uuid END AS punishment_type_id,
        CASE WHEN TRUE THEN pt.name ELSE NULL::text END AS punishment_type_name,
        p.triggering_rule_id,
        r.name AS triggering_rule_name,
        CASE WHEN TRUE THEN p.automated ELSE NULL::boolean END AS automated,
        CASE WHEN TRUE THEN p.due_at ELSE NULL::timestamptz END AS due_at,
        p.resolved_at
    FROM punishments p
    JOIN punishment_types pt ON pt.id = p.punishment_type_id
    LEFT JOIN rules r ON r.id = p.triggering_rule_id AND r.user_id = p.user_id
    WHERE p.student_id = $1
      AND p.user_id = $2

    UNION ALL

    SELECT
        'penalty'::text AS type,
        p.id,
        p.created_at,
        p.occurred_at,
        p.evaluation_label,
        p.penalty_type_id,
        pt.name AS penalty_type_name,
        NULL::uuid AS bonus_type_id,
        NULL::text AS bonus_type_name,
        NULL::double precision AS points,
        NULL::timestamptz AS used_at,
        p.penalty_type_id AS punishment_type_id,
        pt.name AS punishment_type_name,
        NULL::uuid AS triggering_rule_id,
        NULL::text AS triggering_rule_name,
        FALSE AS automated,
        p.occurred_at AS due_at,
        NULL::timestamptz AS resolved_at
    FROM penalties p
    JOIN penalty_types pt ON pt.id = p.penalty_type_id
    WHERE p.student_id = $1
      AND p.user_id = $2

    UNION ALL

    SELECT
        'bonus'::text AS type,
        b.id,
        b.created_at,
        b.occurred_at,
        b.evaluation_label,
        NULL::uuid AS penalty_type_id,
        NULL::text AS penalty_type_name,
        b.bonus_type_id,
        bt.name AS bonus_type_name,
        b.points,
        b.used_at,
        b.bonus_type_id AS punishment_type_id,
        bt.name AS punishment_type_name,
        NULL::uuid AS triggering_rule_id,
        NULL::text AS triggering_rule_name,
        FALSE AS automated,
        b.occurred_at AS due_at,
        NULL::timestamptz AS resolved_at
    FROM bonuses b
    JOIN bonus_types bt ON bt.id = b.bonus_type_id
    WHERE b.student_id = $1
      AND b.user_id = $2
) history
ORDER BY history.occurred_at DESC, history.id DESC
LIMIT $4 OFFSET $3
`

type ListStudentHistoryParams struct {
	StudentID   uuid.UUID `json:"student_id"`
	UserID      uuid.UUID `json:"user_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListStudentHistoryRow struct {
	Type               string     `json:"type"`
	ID                 uuid.UUID  `json:"id"`
	CreatedAt          time.Time  `json:"created_at"`
	OccurredAt         time.Time  `json:"occurred_at"`
	EvaluationLabel    string     `json:"evaluation_label"`
	PenaltyTypeID      *uuid.UUID `json:"penalty_type_id"`
	PenaltyTypeName    *string    `json:"penalty_type_name"`
	BonusTypeID        *uuid.UUID `json:"bonus_type_id"`
	BonusTypeName      *string    `json:"bonus_type_name"`
	Points             *float64   `json:"points"`
	UsedAt             *time.Time `json:"used_at"`
	PunishmentTypeID   uuid.UUID  `json:"punishment_type_id"`
	PunishmentTypeName string     `json:"punishment_type_name"`
	TriggeringRuleID   *uuid.UUID `json:"triggering_rule_id"`
	TriggeringRuleName *string    `json:"triggering_rule_name"`
	Automated          bool       `json:"automated"`
	DueAt              time.Time  `json:"due_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
}

func (q *Queries) ListStudentHistory(ctx context.Context, arg ListStudentHistoryParams) ([]ListStudentHistoryRow, error) {
	rows, err := q.db.Query(ctx, listStudentHistory,
		arg.StudentID,
		arg.UserID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentHistoryRow
	for rows.Next() {
		var i ListStudentHistoryRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.CreatedAt,
			&i.OccurredAt,
			&i.EvaluationLabel,
			&i.PenaltyTypeID,
			&i.PenaltyTypeName,
			&i.BonusTypeID,
			&i.BonusTypeName,
			&i.Points,
			&i.UsedAt,
			&i.PunishmentTypeID,
			&i.PunishmentTypeName,
			&i.TriggeringRuleID,
			&i.TriggeringRuleName,
			&i.Automated,
			&i.DueAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
