// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student_classrooms.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addStudentToClassroom = `-- name: AddStudentToClassroom :execrows

INSERT INTO student_classrooms (user_id, student_id, classroom_id)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1 FROM students st WHERE st.id = $2 AND st.user_id = $1
) AND EXISTS (
    SELECT 1 FROM classrooms cl WHERE cl.id = $3 AND cl.user_id = $1
)
`

type AddStudentToClassroomParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StudentID   uuid.UUID `json:"student_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
}

// ==================== StudentClassroom ====================
func (q *Queries) AddStudentToClassroom(ctx context.Context, arg AddStudentToClassroomParams) (int64, error) {
	result, err := q.db.Exec(ctx, addStudentToClassroom, arg.UserID, arg.StudentID, arg.ClassroomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countClassroomsByStudent = `-- name: CountClassroomsByStudent :one
SELECT COUNT(*)
FROM student_classrooms sc
JOIN students s ON s.id = sc.student_id AND s.user_id = sc.user_id
JOIN classrooms c ON c.id = sc.classroom_id AND c.user_id = sc.user_id
WHERE sc.user_id = $1
  AND sc.student_id = $2
`

type CountClassroomsByStudentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) CountClassroomsByStudent(ctx context.Context, arg CountClassroomsByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClassroomsByStudent, arg.UserID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsByClassroom = `-- name: CountStudentsByClassroom :one
SELECT COUNT(*)
FROM student_classrooms sc
JOIN students s ON s.id = sc.student_id AND s.user_id = sc.user_id
JOIN classrooms c ON c.id = sc.classroom_id AND c.user_id = sc.user_id
WHERE sc.user_id = $1
  AND sc.classroom_id = $2
  AND (
    $3::text IS NULL
    OR CONCAT_WS(' ', s.first_name, s.last_name) ILIKE '%' || $3::text || '%'
  )
`

type CountStudentsByClassroomParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
	Search      *string   `json:"search"`
}

func (q *Queries) CountStudentsByClassroom(ctx context.Context, arg CountStudentsByClassroomParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsByClassroom, arg.UserID, arg.ClassroomID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listClassroomRefsByStudentIDs = `-- name: ListClassroomRefsByStudentIDs :many
SELECT
    sc.student_id,
    c.id AS classroom_id,
    c.name AS classroom_name
FROM student_classrooms sc
JOIN classrooms c ON c.id = sc.classroom_id AND c.user_id = sc.user_id
JOIN students s ON s.id = sc.student_id AND s.user_id = sc.user_id
WHERE sc.user_id = $1
  AND sc.student_id = ANY($2::uuid[])
ORDER BY c.created_at DESC
`

type ListClassroomRefsByStudentIDsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	StudentIds []uuid.UUID `json:"student_ids"`
}

type ListClassroomRefsByStudentIDsRow struct {
	StudentID     uuid.UUID `json:"student_id"`
	ClassroomID   uuid.UUID `json:"classroom_id"`
	ClassroomName string    `json:"classroom_name"`
}

func (q *Queries) ListClassroomRefsByStudentIDs(ctx context.Context, arg ListClassroomRefsByStudentIDsParams) ([]ListClassroomRefsByStudentIDsRow, error) {
	rows, err := q.db.Query(ctx, listClassroomRefsByStudentIDs, arg.UserID, arg.StudentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassroomRefsByStudentIDsRow
	for rows.Next() {
		var i ListClassroomRefsByStudentIDsRow
		if err := rows.Scan(&i.StudentID, &i.ClassroomID, &i.ClassroomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassroomsByStudent = `-- name: ListClassroomsByStudent :many
SELECT
    c.id, c.user_id, c.name, c.year, c.main_teacher, c.created_at, c.updated_at,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc2
        WHERE sc2.classroom_id = c.id
          AND sc2.user_id = c.user_id
    ), 0)::bigint AS student_count,
    COALESCE((
        SELECT SUM(b.points)
        FROM student_classrooms sc2
        JOIN students s2 ON s2.id = sc2.student_id AND s2.user_id = sc2.user_id
        JOIN bonuses b ON b.student_id = s2.id AND b.user_id = s2.user_id
        WHERE sc2.classroom_id = c.id
          AND sc2.user_id = c.user_id
          AND b.user_id = c.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS total_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM student_classrooms sc2
        JOIN students s2 ON s2.id = sc2.student_id AND s2.user_id = sc2.user_id
        JOIN penalties p ON p.student_id = s2.id AND p.user_id = s2.user_id
        WHERE sc2.classroom_id = c.id
          AND sc2.user_id = c.user_id
          AND p.user_id = c.user_id
    ), 0)::bigint AS total_penalty_count
FROM classrooms c
JOIN student_classrooms sc ON sc.classroom_id = c.id AND sc.user_id = c.user_id
JOIN students s ON s.id = sc.student_id AND s.user_id = sc.user_id
WHERE sc.user_id = $1
  AND sc.student_id = $2
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type ListClassroomsByStudentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StudentID   uuid.UUID `json:"student_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListClassroomsByStudentRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Year              *string   `json:"year"`
	MainTeacher       *string   `json:"main_teacher"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	StudentCount      int64     `json:"student_count"`
	TotalBonusPoints  float64   `json:"total_bonus_points"`
	TotalPenaltyCount int64     `json:"total_penalty_count"`
}

func (q *Queries) ListClassroomsByStudent(ctx context.Context, arg ListClassroomsByStudentParams) ([]ListClassroomsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listClassroomsByStudent,
		arg.UserID,
		arg.StudentID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassroomsByStudentRow
	for rows.Next() {
		var i ListClassroomsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Year,
			&i.MainTeacher,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentCount,
			&i.TotalBonusPoints,
			&i.TotalPenaltyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByClassroom = `-- name: ListStudentsByClassroom :many
SELECT
    s.id, s.user_id, s.first_name, s.last_name, s.created_at, s.updated_at,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = s.id
          AND b.user_id = s.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = s.id
          AND p.user_id = s.user_id
    ), 0)::bigint AS penalty_count
FROM students s
JOIN student_classrooms sc ON sc.student_id = s.id AND sc.user_id = s.user_id
JOIN classrooms c ON c.id = sc.classroom_id AND c.user_id = sc.user_id
WHERE sc.user_id = $1
  AND sc.classroom_id = $2
  AND (
    $3::text IS NULL
    OR CONCAT_WS(' ', s.first_name, s.last_name) ILIKE '%' || $3::text || '%'
  )
ORDER BY s.created_at DESC
LIMIT $5 OFFSET $4
`

type ListStudentsByClassroomParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
	Search      *string   `json:"search"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListStudentsByClassroomRow struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
	FirstName            string    `json:"first_name"`
	LastName             string    `json:"last_name"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	AvailableBonusPoints float64   `json:"available_bonus_points"`
	PenaltyCount         int64     `json:"penalty_count"`
}

func (q *Queries) ListStudentsByClassroom(ctx context.Context, arg ListStudentsByClassroomParams) ([]ListStudentsByClassroomRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByClassroom,
		arg.UserID,
		arg.ClassroomID,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsByClassroomRow
	for rows.Next() {
		var i ListStudentsByClassroomRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableBonusPoints,
			&i.PenaltyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsPreviewByClassroomIDs = `-- name: ListStudentsPreviewByClassroomIDs :many
SELECT
    c.id AS classroom_id,
    preview.student_id,
    preview.first_name,
    preview.last_name
FROM classrooms c
JOIN LATERAL (
    SELECT
        s.id AS student_id,
        s.first_name,
        s.last_name
    FROM student_classrooms sc
    JOIN students s ON s.id = sc.student_id AND s.user_id = sc.user_id
    WHERE sc.user_id = c.user_id
      AND sc.classroom_id = c.id
    ORDER BY s.created_at DESC
    LIMIT $1
) preview ON TRUE
WHERE c.user_id = $2
  AND c.id = ANY($3::uuid[])
ORDER BY c.id
`

type ListStudentsPreviewByClassroomIDsParams struct {
	PreviewLimit int32       `json:"preview_limit"`
	UserID       uuid.UUID   `json:"user_id"`
	ClassroomIds []uuid.UUID `json:"classroom_ids"`
}

type ListStudentsPreviewByClassroomIDsRow struct {
	ClassroomID uuid.UUID `json:"classroom_id"`
	StudentID   uuid.UUID `json:"student_id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
}

func (q *Queries) ListStudentsPreviewByClassroomIDs(ctx context.Context, arg ListStudentsPreviewByClassroomIDsParams) ([]ListStudentsPreviewByClassroomIDsRow, error) {
	rows, err := q.db.Query(ctx, listStudentsPreviewByClassroomIDs, arg.PreviewLimit, arg.UserID, arg.ClassroomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsPreviewByClassroomIDsRow
	for rows.Next() {
		var i ListStudentsPreviewByClassroomIDsRow
		if err := rows.Scan(
			&i.ClassroomID,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudentFromClassroom = `-- name: RemoveStudentFromClassroom :execrows
DELETE FROM student_classrooms
WHERE user_id = $1
  AND student_id = $2
  AND classroom_id = $3
`

type RemoveStudentFromClassroomParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StudentID   uuid.UUID `json:"student_id"`
	ClassroomID uuid.UUID `json:"classroom_id"`
}

func (q *Queries) RemoveStudentFromClassroom(ctx context.Context, arg RemoveStudentFromClassroomParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeStudentFromClassroom, arg.UserID, arg.StudentID, arg.ClassroomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
