// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStudentsByUser = `-- name: CountStudentsByUser :one
SELECT COUNT(*)
FROM students s
WHERE s.user_id = $1
  AND (
    $2::text IS NULL
    OR CONCAT_WS(' ', s.first_name, s.last_name) ILIKE '%' || $2::text || '%'
  )
`

type CountStudentsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Search *string   `json:"search"`
}

func (q *Queries) CountStudentsByUser(ctx context.Context, arg CountStudentsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsByUser, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one

INSERT INTO students (
    user_id, first_name, last_name
) VALUES (
    $1, $2, $3
)
RETURNING
    id, user_id, first_name, last_name, created_at, updated_at,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = students.id
          AND b.user_id = students.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = students.id
          AND p.user_id = students.user_id
    ), 0)::bigint AS penalty_count
`

type CreateStudentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

type CreateStudentRow struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
	FirstName            string    `json:"first_name"`
	LastName             string    `json:"last_name"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	AvailableBonusPoints float64   `json:"available_bonus_points"`
	PenaltyCount         int64     `json:"penalty_count"`
}

// ==================== Student ====================
func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (CreateStudentRow, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.UserID, arg.FirstName, arg.LastName)
	var i CreateStudentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableBonusPoints,
		&i.PenaltyCount,
	)
	return i, err
}

const deleteAllStudentsByUser = `-- name: DeleteAllStudentsByUser :execrows
DELETE FROM students
WHERE user_id = $1
`

func (q *Queries) DeleteAllStudentsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllStudentsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStudentByUser = `-- name: DeleteStudentByUser :execrows
DELETE FROM students
WHERE id = $1 AND user_id = $2
`

type DeleteStudentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStudentByUser(ctx context.Context, arg DeleteStudentByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudentByUser = `-- name: GetStudentByUser :one
SELECT
    s.id, s.user_id, s.first_name, s.last_name, s.created_at, s.updated_at,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = s.id
          AND b.user_id = s.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = s.id
          AND p.user_id = s.user_id
    ), 0)::bigint AS penalty_count
FROM students s
WHERE s.id = $1 AND s.user_id = $2 LIMIT 1
`

type GetStudentByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetStudentByUserRow struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
	FirstName            string    `json:"first_name"`
	LastName             string    `json:"last_name"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	AvailableBonusPoints float64   `json:"available_bonus_points"`
	PenaltyCount         int64     `json:"penalty_count"`
}

func (q *Queries) GetStudentByUser(ctx context.Context, arg GetStudentByUserParams) (GetStudentByUserRow, error) {
	row := q.db.QueryRow(ctx, getStudentByUser, arg.ID, arg.UserID)
	var i GetStudentByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableBonusPoints,
		&i.PenaltyCount,
	)
	return i, err
}

const listStudentsByUser = `-- name: ListStudentsByUser :many
SELECT
    s.id, s.user_id, s.first_name, s.last_name, s.created_at, s.updated_at,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = s.id
          AND b.user_id = s.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = s.id
          AND p.user_id = s.user_id
    ), 0)::bigint AS penalty_count
FROM students s
WHERE s.user_id = $1
  AND (
    $2::text IS NULL
    OR CONCAT_WS(' ', s.first_name, s.last_name) ILIKE '%' || $2::text || '%'
  )
ORDER BY s.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStudentsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Search      *string   `json:"search"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

type ListStudentsByUserRow struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
	FirstName            string    `json:"first_name"`
	LastName             string    `json:"last_name"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	AvailableBonusPoints float64   `json:"available_bonus_points"`
	PenaltyCount         int64     `json:"penalty_count"`
}

func (q *Queries) ListStudentsByUser(ctx context.Context, arg ListStudentsByUserParams) ([]ListStudentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByUser,
		arg.UserID,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsByUserRow
	for rows.Next() {
		var i ListStudentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableBonusPoints,
			&i.PenaltyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentByUser = `-- name: UpdateStudentByUser :one
UPDATE students
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    updated_at = NOW()
WHERE students.id = $3 AND students.user_id = $4
RETURNING
    students.id, students.user_id, students.first_name, students.last_name, students.created_at, students.updated_at,
    COALESCE((
        SELECT SUM(b.points)
        FROM bonuses b
        WHERE b.student_id = students.id
          AND b.user_id = students.user_id
          AND b.used_at IS NULL
    ), 0)::double precision AS available_bonus_points,
    COALESCE((
        SELECT COUNT(*)
        FROM penalties p
        WHERE p.student_id = students.id
          AND p.user_id = students.user_id
    ), 0)::bigint AS penalty_count
`

type UpdateStudentByUserParams struct {
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
}

type UpdateStudentByUserRow struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
	FirstName            string    `json:"first_name"`
	LastName             string    `json:"last_name"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	AvailableBonusPoints float64   `json:"available_bonus_points"`
	PenaltyCount         int64     `json:"penalty_count"`
}

func (q *Queries) UpdateStudentByUser(ctx context.Context, arg UpdateStudentByUserParams) (UpdateStudentByUserRow, error) {
	row := q.db.QueryRow(ctx, updateStudentByUser,
		arg.FirstName,
		arg.LastName,
		arg.ID,
		arg.UserID,
	)
	var i UpdateStudentByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableBonusPoints,
		&i.PenaltyCount,
	)
	return i, err
}
